### ISSUE TITLE
Monaco

### ISSUE THREAD

**Issue by duncanparkes** [everypolitician/everypolitician-data#103]
Looks easy enough: http://www.conseil-national.mc/index.php/les-elus/les-groupes-politiques

**Comment by tmtmtmtm** [comment]
And gender too, which is handy.

**Comment by duncanparkes** [comment]
Some scraped data here: https://morph.io/duncanparkes/monaco

There are more things that could be captured, as always. In particular, I've not tried to turn the French DOB into a date object.

**Comment by duncanparkes** [comment]
I've added a table containing a single line for the term for you. It's just based on the years for the moment, because I can't see dates and it always feels risky to base a term on the election date.

**Comment by tmtmtmtm** [comment]
Thanks. Was there a reason for not grabbing the historic data? They look pretty easy too:
- http://www.conseil-national.mc/index.php/la-vie-parlementaire/histoire-du-conseil-national/les-elus-de-la-legislature-2008-2013
- http://www.conseil-national.mc/index.php/la-vie-parlementaire/histoire-du-conseil-national/les-elus-de-la-legislature-2003-2008

**Comment by tmtmtmtm** [comment]
Looks like 2013-02-21 was the start date: http://www.conseil-national.mc/index.php/rediffusions-de-2013/session-extraordinaire-2013/21-fevrier-2013-seance-publique-session-speciale-investiture

**Comment by duncanparkes** [comment]
Just didn't spot it  - your French is probably better than mine!

**Comment by tmtmtmtm** [comment]
I just used Google Translate :)

**Comment by duncanparkes** [comment]
In a few cases I think we can come up with a firm date for the start of the session, but only a year for the end - the start of the session is often in hansard, but the end may not even be known. Do you cope OK if we have a date for the start and just and integer year for the end?

**Comment by tmtmtmtm** [comment]
Yep — that should work fine.

**Comment by tmtmtmtm** [comment]
What's the status of this? Is it ready now?

**Comment by duncanparkes** [comment]
Yes, I believe this is ready.

**Comment by tmtmtmtm** [comment]
Only real problem here is that one the terms has a name of "2013-1018", rather than 2018.

However, if you were fixing that, then changing `details_url` to `source` and `term_id` to `term` (in the data table — the terms table is fine) whilst you're there would mean I wouldn't have to remap those manually.

**Comment by tmtmtmtm** [comment]
Ah, no the party information is all jumbled too:

![monaco parties](https://cloud.githubusercontent.com/assets/57483/8125956/51bac5e0-10e2-11e5-8167-cdc6427ac251.png)

I can't really tell whether that's something that's would be fairly trivial for you to clean up at your end, or whether it would be simpler for now to just post-process it.

**Comment by duncanparkes** [comment]
I think the duplicate parties should be merged as of b5ac32d4e141b87d0dd33d3453909fba86aac1fe

I've also changed the term name.

**Comment by tmtmtmtm** [comment]
Thanks — this is live at http://data.everypolitician.org/monaco/

It would be very useful, however, for Independents to be explicitly marked as such, as at the minute they have no party information at all, and thus go in as "unknown" — e.g. http://data.everypolitician.org/monaco/term_table/2008.html

**Comment by duncanparkes** [comment]
I've make a quick and dirty fix to get Indepndent for the three Sans Etiquette members, and to get a Party for Stephane Valeri in 2003, in case you want to reimport.

**Comment by tmtmtmtm** [comment]
Thanks. Merged as https://github.com/everypolitician/everypolitician-data/pull/288
