### ISSUE TITLE
Armenia: Extract MP id's

### ISSUE THREAD

**Issue by marfi** [everypolitician/everypolitician-data#109639]
The Armenian Assembly seems to have pretty good website where the photos of the MPs contain their IDs. (The same IDs EP assigns to the MPs).

The format is: [1-9]\d* and they can be then decoded here:
http://www.parliament.am/deputies.php?sel=details&ID=$1&lang=eng

replace the $1 with the id.

**Comment by tmtmtmtm** [comment]
hi @marfi — sorry for slow response; I missed this request when it first came through :(

From what I can tell this ID isn't stable — people are given a new one in each term. See for example:
* http://www.parliament.am/deputies.php?sel=details&ID=23&lang=eng
* http://www.parliament.am/deputies.php?sel=details&ID=938&lang=eng
* http://www.parliament.am/deputies.php?sel=details&ID=1052&lang=eng

**Comment by marfi** [comment]
Good find, missed that aspect.

Closing it for now, until I figure out a way they could be used.
