### ISSUE TITLE
Ukraine

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#111]
http://w1.c1.rada.gov.ua/pls/site2/p_deputat_list

includes 7 previous convocations, back to 1990

**Comment by tmtmtmtm** [comment]
The actual lists are injected via JavaScript but can be fetched as

* http://w1.c1.rada.gov.ua/pls/site2/fetch_mps?skl_id=8 (VII скликання (2012-2014))
* http://w1.c1.rada.gov.ua/pls/site2/fetch_mps?skl_id=7 (VI скликання (2007-2012))
* http://w1.c1.rada.gov.ua/pls/site2/fetch_mps?skl_id=6 (V скликання (2006-2007))
* http://w1.c1.rada.gov.ua/pls/site2/fetch_mps?skl_id=5 (IV скликання (2002-2006))

Earlier terms use a different format:
* http://w1.c1.rada.gov.ua/pls/radan_gs09/d_index_arh?skl=3 (3-го скликання (1998-2002))
* http://w1.c1.rada.gov.ua/pls/radan_gs09/d_index_arh?skl=2 (2-го скликання (1994-1998))
* http://static.rada.gov.ua/zakon/new/NEWSAIT/DEPUTAT1/spisok1.htm (1-го скликання (1990-1994))

Ukrainian Wikipedia also has good data: e.g. https://uk.wikipedia.org/wiki/Верховна_Рада_України_VII_скликання

**Comment by henare** [comment]
I've [started work on this](https://morph.io/openaustralia/ukraine_verkhovna_rada_deputies) for a project we're working on.

Any hints/tips/suggested changes very gladly accepted!

**Comment by tmtmtmtm** [comment]
@henare: Are you getting the data in English, Ukrainian, or both?

**Comment by henare** [comment]
@tmtmtmtm Ukrainian will be what we're using on our project and it's what I'm starting to collect. What's most useful for EveryPolitician?

**Comment by tmtmtmtm** [comment]
Ideally both. We still haven't worked out the best way to handle multi-lingual stuff, but at least if we _have_ it, we can work out later what to do with it. It's also very handy for doing fuzzy-matching with info from other sources. As the official site doesn't seem to have an English equivalent (where we might be able to match by a shared ID or image URL), I suspect what I'd do is try to match the Ukrainian data with the Wikipedia version, as once we have Wikipedia titles for everyone, then Wikidata should give us lots of multi-lingual info. I'm not sure what the process of fuzzy name matching between the official source and the Wikipedia versions of their names will be like though. We use https://github.com/seamusabshere/fuzzy_match for that (with thresholds that are configurable per source — e..g https://github.com/everypolitician/everypolitician-data/blob/f52d1fb4d3d18da9b62f0bcde906a08486538d7b/data/Belgium/Representatives/sources/instructions.json#L22-L26), but I haven't tried it with non-Latin text yet.

**Comment by henare** [comment]
Cool. I'll focus on the Ukrainian data first and we can expand it to English later.

Oddly in #734 I'm naming the house in English - this is to be consistent with the rest of the repo and feels like the right thing to do.

**Comment by tmtmtmtm** [comment]
One of the reasons for wanting the Wikidata ID in the `meta.json` is so that we can do those translations automagically. I've been ensuring that all newly-added countries have them for a while, but only cleared the backlog of old ones that didn't have them at the weekend (https://github.com/everypolitician/everypolitician-data/issues/702). Once the GLOW push is over, doing something clever with those is high on the priority list.

**Comment by tmtmtmtm** [comment]
@henare I knocked up a quick scraper for the Wikipedia version: https://morph.io/tmtmtmtm/ukraine-deputies-wikipedia

It only gets the current members of the current term at the minute, but should be fairly easy to extend. If I get a break later today I'll try cross-matching the names.

**Comment by tmtmtmtm** [comment]
Actually, while I was here I thought I should probably get the deputies who have left early as well. Now updated for that.
