### ISSUE TITLE
DRC

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#113]
http://www.assemblee-nationale.cd/v2/?page_id=4087

**Comment by tmtmtmtm** [comment]
This doesn't seem to list the Party or Constituency of any of the Members…

**Comment by tmtmtmtm** [comment]
http://www.assemblee-nationale.cd/v2/?team=lokondo-yoka-henri-thomas is an example of what an MP *should* contain — but more are just blank.

**Comment by rubeenam** [comment]
http://psephos.adam-carr.net/countries/c/congodemrep/leg2006/mongala.txt

National Assembly members, party and constituency for 2006 election

Also a Wikipedia list on the same 

https://en.m.wikipedia.org/wiki/Members_of_the_National_Assembly_of_the_Democratic_Republic_of_the_Congo_2006-2011

**Comment by tmtmtmtm** [comment]
No joy on finding anything for the 2011 election?

(NB: That Psephos page is only for one province: all the others are listed at http://psephos.adam-carr.net/countries/c/congodemrep/congo2006index.shtml)

**Comment by rubeenam** [comment]
Oh yes sorry, I pasted the wrong link.

**Comment by FOIMonkey** [comment]
http://www.telema.org/pdf/telema_senateurs_rdc.pdf
http://www.telema.org/pdf/telema_deputes_rdc.pdf

Sadly image based PDFs, but the data seems to match the parliament site.

**Comment by tmtmtmtm** [comment]
http://www.onlineocr.net/ did a remarkably good job on the Deputies PDF. I converted it to Excel, imported to Google Sheets, and tidied up a few that it had trouble with: https://docs.google.com/spreadsheets/d/1VNu0F8loXEv5AhXiWdwLrajpY_aPTOVAHOaTddb323w/edit?usp=sharing

There are probably a whole bunch of other little things that need tidied in it, but it looks good to work with. Anyone who wants edit permissions to help tidying, email team@everypolitician.org

**Comment by tmtmtmtm** [comment]
* https://en.wikipedia.org/wiki/National_Assembly_(Democratic_Republic_of_the_Congo)
* https://www.wikidata.org/wiki/Q1574334
* 500 seats
