### ISSUE TITLE
Romania

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#115]
http://www.cdep.ro/pls/parlam/structura2015.de?idl=2 

7 terms

**Comment by tmtmtmtm** [comment]
Some data can be obtained from http://parlament.openpolitics.ro/export/, including voting records, but there seems to be more basic data on the official site.

**Comment by tmtmtmtm** [comment]
* WIP at https://github.com/tmtmtmtm/romanian-parliament
* need to match the same person being in multiple terms
* need to cope with changing Parliamentary groups
* Odd special case: http://www.cdep.ro/pls/parlam/structura2015.mp?idm=210&cam=2&leg=1996&idl=2

**Comment by briatte** [comment]
My own attempt to deal with that mess is [there](https://github.com/briatte/parlamentul/blob/master/data.r). Note that many Senators are former MPs, so if you scrape mandates, you have to scrape them for each chamber.

My scraper covers everything since 1996 in both chambers.
