### ISSUE TITLE
Iraq

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#117]
http://www.parliament.iq/Representative.aspx

(Also has English version, but it's JavaScript driven and doesn't seem to work very well) — could do with finding another source.

**Comment by tmtmtmtm** [comment]
http://www.iraqiparliament.info/en/members looks like a better source

**Comment by FOIMonkey** [comment]
http://www.miqpm.com/new/Memberships_Index.php?ID=12

**Comment by tmtmtmtm** [comment]
Woo — thanks @FOIMonkey

**Comment by tmtmtmtm** [comment]
* https://en.wikipedia.org/wiki/Council_of_Representatives_of_Iraq
* https://www.wikidata.org/wiki/Q1973075
* Members: 328
