### ISSUE TITLE
Northern Cyprus: add birth dates

### ISSUE THREAD

**Issue by wfdd** [everypolitician/everypolitician-data#11932]
The instructions file could be updated to pick up the birth dates (years) from https://morph.io/wfdd/nc-assembly-scraper.

**Comment by wfdd** [comment]
I would have done but the repo is enormous.  I guess I could use the GitHub web interface...

**Comment by wfdd** [comment]
Righty-o, you can clone just the latest version with `--depth` in git.  Much better.

**Comment by tmtmtmtm** [comment]
Yep. Beware that that means you won't be able to do Step 3 of the instructions (building the `countries.json` file), as that requires a git history. But you can merrily skip that step anyway, as the bot will automatically add that for you once the pull request is opened.

We should really actually remove that section of the docs, or at least note that it's optional now (ping @davewhiteland)

**Comment by wfdd** [comment]
Hopefully I've not messed everything up too badly ;)
