### ISSUE TITLE
Spain: Scrape official site

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#1227]
proyectocolibri.es has disappeared (and was missing some info too), so we should scrape the [official site](http://www.congreso.es/portal/page/portal/Congreso/Congreso/Diputados?_piref73_1333056_73_1333049_1333049.next_page=/wc/menuAbecedarioInicio&tipoBusqueda=completo&idLegislatura=11)

(we can get both current and historic information)

**Comment by struan** [comment]
Morph scraper at https://morph.io/struan/spain_congreso_es

Hasn't got all the data yet because of a server error but it has enough to check.

**Comment by tmtmtmtm** [comment]
Thanks @struan 

We should probably catch the errors and just warn on them, rather than break completely when it fails.

A few other things:

* The part that's generating the various name aspects doesn't seem right: it's ending up with data like: 
`:name=>"Angulo Romero  María Teresa", :sort_name=>"Angulo Romero, María Teresa", :given_name=>"Angulo Romero  María Teresa", :family_name=>""`. I think you just need to split the name string on the comma, rather than partitioning based on upper and lower casing
* Would be useful to split the faction info so that instead of `:faction=>"G.P. Popular ( GP )",` we have `:faction=>"G.P. Popular", :faction_id=>"GP"`
* The constituency would be better as just `:constituency=>"Huesca"` rather than `:constituency=>"Diputada por Huesca."`
* I'm assuming the "Fecha alta" and "Causó baja" are the `start_date` and `end_date` of the Memberships, in which case it's important to grab them

If you want me to take this over and add those, let me know.

**Comment by struan** [comment]
Shall we see how it goes with the other stuff I'm doing and I can let you know later in the week if it looks like I have time to pick this up?

**Comment by tmtmtmtm** [comment]
Sure. One other key problem is there doesn't seem to be anything at the minute to tie together the various entries for a single person — i.e. to say that person 199 in term 11 == person 222 in term 10 == person 1 in term 9 == person 260 in term 8. I'm not sure if they're available in some other way, but the "Todas las legislaturas" goes to a page that lists all of the relevant combinations for that person.

It would also be good if this picked up other links / contact details like facebook, website, phone, and fax (all appear on http://www.congreso.es/portal/page/portal/Congreso/Congreso/Diputados/BusqForm?_piref73_1333155_73_1333154_1333154.next_page=/wc/fichaDiputado&idLegislatura=11&idDiputado=199)

**Comment by tmtmtmtm** [comment]
There are also a bunch of places where the group information seems broken in the source: e.g. http://www.congreso.es/portal/page/portal/Congreso/Congreso/Diputados/BusqForm?_piref73_1333155_73_1333154_1333154.next_page=/wc/fichaDiputado?idDiputado=194&idLegislatura=11

These should probably just set `nil` there, rather than a string value of "null".

**Comment by tmtmtmtm** [comment]
This is essentially done, though there are ongoing problems with the scraper.
