### ISSUE TITLE
Tunisia

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#123]
easiest way seems to be to get them by Bloc:
  http://www.arp.tn/site/main/AR/docs/groupes/liste_groupes.jsp

(Though should double check there aren't people not in any faction)

**Comment by briatte** [comment]
You might want to look at [this](http://majles.marsad.tn/fr/assemblee) (2011 election) and [this](http://majles.marsad.tn/2014/fr/assemblee) (2014 election). The `data` tags are very easy to use, and have only few missing values.

**Comment by tmtmtmtm** [comment]
@briatte thanks! That definitely looks simple and useful. Will try grabbing that later today.

**Comment by tmtmtmtm** [comment]
https://morph.io/tmtmtmtm/tunisia-marsad now gets the 2014 data

**Comment by tmtmtmtm** [comment]
I'm now scraping both, but I'll probably only import the 2014 data for now, as the 2011 data is technically for a different legislature (the Chamber of Deputies, rather than the Assembly of the Representatives of the People), and I don't have a good way yet of correctly marking that someone in one legislature is the same person as someone in a different one. It's on the list to fix fairly soon, so I'll defer importing the historic ones until then.

**Comment by briatte** [comment]
The 2011 assembly is the Constituent Assembly. If you look at the political blocs, there's only one constant bloc throughout both chambers (Nahdha, plus the "no bloc" category).

The combination of first and family names returns unique ids in each legislature (no duplicated "John Smiths"). 28 MPs from the 2011 election are still in office after the 2014 election:

```
    Abdelaziz Kotti     Ahmed Mechergui      Ameur Laraiedh        Basma Jebali        Dalila Babba 
                  2                   2                   2                   2                   2 
        Fathi Ayadi       Habib Khedher     Hedi Ben Braham          Hela Hammi     Imen Ben Mhamed 
                  2                   2                   2                   2                   2 
Kalthoum Badreddine      Latifa Habachi       Mabrouk Hrizi      Mahmoud Gouiaa   Mehdi Ben Gharbia 
                  2                   2                   2                   2                   2 
 Moez Belhaj Rhouma        Mohamed Zrig        Mongi Rahoui           Neji Jmal   Noureddine Mrabti 
                  2                   2                   2                   2                   2 
  Oussama Al Saghir         Rim Mahjoub          Rim Thairi          Sahbi Atig         Samia Abbou 
                  2                   2                   2                   2                   2 
        Sana Mersni     Soulef Ksantini     Yamina Zoghlami 
                  2                   2                   2
```

I trust Marsad with using the same names across both chambers. Their data is top notch AFAICT.

**Comment by tmtmtmtm** [comment]
Ah, yes, I misread the history there. As I understand it the Constituent Assembly is still technically different from the current Assembly, though, no? The 2014 version is listed as the "1st legislature". Or can the 2011 version be classed as the "0th" legislature of the same body?

On naming: In general I'm OK with assuming that someone with the same name across two consecutive terms is _probably_ going to be the same person, and manually resolving cases later when they're not. My issue is more that we currently have no way in EveryPolitician of designating two people in different legislatures as being actually the same person — e.g. that the Gerry Adams who used to be in the UK House of Commons is the same person as the Gerry Adams who's currently in the Irish Dáil. So If I made the Constituent Assembly a different legislature from the Assembly of the Representatives of the People, I would currently have no way of saying that "Latifa Habachi", for example, is the same person in both. That's probably not a massive problem in most cases, but I'd like to resolve it.

**Comment by briatte** [comment]
> As I understand it the Constituent Assembly is still technically different from the current Assembly, though, no?

Yes, because its term ends with the vote on a constitutional agreement. The same assembly also had to agree on electoral law. The current legislature is the first legislature to be elected under that law, which is why it's numbered "1". Same thing for the Czech Republic and Slovakia after they split up, or most post-Soviet countries after independence.

> Can the 2011 version be classed as the "0th" legislature of the same body?

That would be more or less correct, given that there is some overlap between both chambers (the Constituent members were not forbidden to run again, and some of them did).

> On naming: In general I'm OK with assuming that someone with the same name across two consecutive terms is probably going to be the same person, and manually resolving cases later when they're not.

That's how I work it too, although I prefer to rely on unique URLs. The best system I've seen is a URL that contains (1) a perfectly unique identifier number and (2) a legislature number. In that case, it's like working with standard longitudinal data. Very few parliaments track their MPs that way, which makes constituency and party transitions a real mess (not to talk about intra-legislature transitions, like Austrian MPs switching parties to follow Haider in his new formation).

> My issue is more that we currently have no way in EveryPolitician of designating two people in different legislatures as being actually the same person — e.g. that the Gerry Adams who used to be in the UK House of Commons is the same person as the Gerry Adams who's currently in the Irish Dáil.

I see what you mean. It's a tough challenge. It's hard enough to track identical people between two chambers in the same country (e.g. MPs who become senators – happens a lot in Italy and Romania, for instance). My guess is that you can let the people reusing the data deal with that.

The big, _big_ thing, really, is to make the data linkable to other forms of data, e.g. voting records, sponsorship records, financial records, whatever. This is what makes the data useful for reuse. Constituencies, for instance, can very often be coded as Wikipedia handles–which makes it possible to connect them to other information, like population demographics and so on.

I have more ideas and suggestions, based on assembling the `parlnet` project, but I'd prefer to hear more about what Every Politician is trying to achieve first. The stated objective of counting women seems very limited—at best, it will produce a slightly more precise figure than the otherwise pretty accurate ones produced by the Inter-Parliamentary Union.

**Comment by tmtmtmtm** [comment]
> The big, big thing, really, is to make the data linkable to other forms of data, e.g. voting records, sponsorship records, financial records, whatever. This is what makes the data useful for reuse. Constituencies, for instance, can very often be coded as Wikipedia handles–which makes it possible to connect them to other information, like population demographics and so on.

Yep — that's the main thing I'm trying to get by connecting with Wikidata. If you look at the columns on https://morph.io/tmtmtmtm/france-chamber-of-deputies-wikidata, for example, the majority of them are other identifiers, so that people can cross-match with other sources. All of the entries there have a sycomore ID, which should cross-reference cleanly with the official National Assembly site. (I haven't integrated that data into EveryPolitician yet, but hopefully should in the next day or so)

> I have more ideas and suggestions, based on assembling the parlnet project, but I'd prefer to hear more about what Every Politician is trying to achieve first. The stated objective of counting women seems very limited—at best, it will produce a slightly more precise figure than the otherwise pretty accurate ones produced by the Inter-Parliamentary Union.

Your comment here crossed with my other email to you, but I'd definitely love to hear those suggestions. 

NB: http://www.gender-balance.org/ is a slightly different project, built on top of EveryPolitician, rather being than the goal of *this* project, but the key advantage over the IPU figures is that we'll have them at a per-person level, rather than just per legislature, thus enabling lots of other types of queries, from what the gender breakdown per Party is, or has been over time, right through to whether women tend to vote differently from men on certain types of issues — or indeed whether they tend to co-sponsor bills with other women at a higher rate, etc.

It's largely also us eating our own dog-food, by making sure it's actually possible to build useful tools on top of the EveryPolitician data, rather than just assuming that the way we make the data available will be automatically useful to everyone else. And it's also an attempt to see what's actually involved in crowd-sourcing a single point of data, across multiple countries, that is often missing from official sources (I'm estimating that only about 10% of countries publish this.)

**Comment by briatte** [comment]
> the key advantage over the IPU figures is that we'll have them at a per-person level, rather than just per legislature, thus enabling lots of other types of queries, from what the gender breakdown per Party is, or has been over time

The gender breakdown by party will be interesting, but it will require coding party affiliations—which can be tough :) It's also important to keep in mind that the gender breakdown in office is only half of the story: the other part is the gender breakdown at the level of electoral candidacy (which is almost impossible to track down).

> right through to whether women tend to vote differently from men on certain types of issues

This is a [very interesting question](https://www.fas.org/sgp/crs/misc/R43244.pdf). Jennifer Clark and Veronica Caro have published some work on that ("[Multimember Districts and the Substantive Representation of Women: An Analysis of Legislative Cosponsorship Networks](https://www.academia.edu/4765164/Multimember_Districts_and_the_Substantive_Representation_of_Women_An_Analysis_of_Legislative_Cosponsorship_Networks)", _Politics and Gender_, 2013), as have [Craig Volden and colleagues](http://www.batten.virginia.edu/content/news/average-women-congress-are-more-effective-lawmakers-men).
