### ISSUE TITLE
store earliest term date in legislature data

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/everypolitician-data#12796]
We're already recording `latest_term`. It would be handy to have `earliest_term` too to be able to more easily see how our historic coverage is doing across legislatures without diving into specific term data.

(I've got a personal agenda here because of the bot blog, but it's something that would be generally useful.)

**Comment by tmtmtmtm** [comment]
@davewhiteland this seems to be opened against the wrong repo

**Comment by davewhiteland** [comment]
Moved to everypolitician/everypolitician#464
