### ISSUE TITLE
Poland: investigate non-Polish chars in incoming party name

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/everypolitician-data#12902]
Specifically, I can't see where "简称SLD" is coming in from

https://github.com/everypolitician/everypolitician-data/blob/master/data/Poland/Sejm/sources/wikidata/groups.json#L1164-L1173
(can't see it Wikidata; maybe it's already been fixed)

```
    {
        "lang": "pl",
        "name": "Sojusz Lewicy Demokratycznej，简称SLD",
        "note": "multilingual"
      },
```

**Comment by tmtmtmtm** [comment]
It's set as an alias on Wikidata, and is still live:

![screen shot 2016-06-24 at 14 54 52](https://cloud.githubusercontent.com/assets/57483/16339676/d279cdda-3a1b-11e6-9162-da6e4d8049ce.png)

https://www.wikidata.org/wiki/Special:EntityData/Q953174.json

You may need to click the "more languages" list to see it in the box at the top of the normal Wikidata page (depending on what you have your default language stack set to)

**Comment by davewhiteland** [comment]
I had tried exactly that route, and not found it, and that was grepping the chars. -- ah, they're cropped off the in the "Also known as" column, pah.

**Comment by davewhiteland** [comment]
Edited on Wikidata, will wait to see that pass through future scraping.
