### ISSUE TITLE
Netherlands

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#130]
Dutch: http://www.tweedekamer.nl/kamerleden/alle_kamerleden
English: http://www.houseofrepresentatives.nl/members_of_parliament/members_of_parliament

**Comment by struan** [comment]
I'm having a look at this.

**Comment by tmtmtmtm** [comment]
https://morph.io/struan/netherlands

@struan — thanks for this. The name munging looks fine, but if you're doing that then you should probably store the parts (as `family_name` and `given_name`) too, and and store the original as a `sort_name` too. 

It would be useful if you could also store the original versions of the faction names as `faction_id`. 

And it would be great if you could get the date of birth and email address from the individual MP pages, and then use those pages as the `source` for each row, and the final component of the URL to their page as the ID for the person (unless there's a better choice for that)
