### ISSUE TITLE
Colombia (Senate)

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/everypolitician-data#13544]
Upper House of the Congress of Colombia:
http://www.secretariasenado.gov.co/index.php/buscar-senador

(out-of-date list for previous term:
https://en.wikipedia.org/wiki/List_of_current_members_of_the_Senate_of_Colombia)

and twitter:
https://github.com/everypolitician-scrapers/twitter-colombia-senate-list/blob/master/scraper.rb +
http://morph.io/everypolitician-scrapers/twitter-colombia-senate-list

**Comment by wfdd** [comment]
It's been a [slow evening](https://morph.io/wfdd/colombia-senado-scraper).

**Comment by wfdd** [comment]
See also http://www.congresovisible.org/congresistas/.

**Comment by wfdd** [comment]
Can be closed now...

**Comment by tmtmtmtm** [comment]
Yep, thanks!
