### ISSUE TITLE
Maldives

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#137]
http://www.majlis.gov.mv/di/members

The English version doesn't have a working link to a Members page

**Comment by rubeenam** [comment]
List of Majlis members by constituency for 2014 election
http://psephos.adam-carr.net/countries/m/maldives/maldives20141.txt

**Comment by tmtmtmtm** [comment]
This all seems quite complex. https://en.wikipedia.org/wiki/Politics_of_the_Maldives says "The total number of the members representing each constituency depends on the total population of that constituency". But https://en.wikipedia.org/wiki/People%27s_Majlis implies that that was before the constitutional changes of 2008, and now _most_ seats are single member, except Male' and the Atolls. However from what I can see Male' and the Atolls are missing from this document (as, in they're there as headlines, but with no data…)

**Comment by rubeenam** [comment]
Addu atoll comprises of several islands in which the candiates are elected and they are the ones listed below it in the document. So addu atoll is like the main heading and the others like Feydhoo, Hithadoo are sub headings under it. Same with other atolls. Mathiaveri, Thoddu come under Alif Alif atoll and so on.

**Comment by rubeenam** [comment]
The document does not make it clear at all. And there is no info on why some islands are electoral districts under an atoll and why some are not.

**Comment by tmtmtmtm** [comment]
Ah, OK. I don't think I can easily work out which are actually part of each (e.g. how many of the following constituencies are part of Male'), but I'm not sure that that matters that much for now. This is probably good enough to start with. Thanks!

**Comment by rubeenam** [comment]
I am going to try and email the election authorities of some countries where I have had no luck in digging out any info. Let's see if they reply!
