### ISSUE TITLE
remove mailto: prefix from email values

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/everypolitician-data#13827]
There are quite a lot of email addresses sneaking in with mailto: prefixes still attached.

Let's strip 'em out (I propose we can be confident that nobody has an email address with mailto: as part of the username, RFC regarding colons notwithstanding).

**Comment by tmtmtmtm** [comment]
@davewhiteland is this about a specific country? Or is this a suggestion for the EP build process generally? 

If it's the latter, this should be moved to `everypolitician/everypolitician`

**Comment by davewhiteland** [comment]
Closed here: re-opened as everypolitician/everypolitician#459
