### ISSUE TITLE
Rewrite New Zealand scraper

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#13824]
https://morph.io/tmtmtmtm/new-zealand-parliament is failing because the official website looks like it's been re-designed.

The new base URL seems to be https://www.parliament.nz/en/mps-and-electorates/members-of-parliament/

**Comment by tmtmtmtm** [comment]
@octopusinvitro you fancy trying this one?

**Comment by octopusinvitro** [comment]
Yes, let me take a look :+1:
