### ISSUE TITLE
Broken Import: Lebanon

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#14067]
## Legislature

Lebanon (Parliament)

## Problem

Imports are failing with:

### Added
- `34deff50-5bf9-47cf-a5a7-f43467c2dba3` - Michael Helou
- `8426d728-6947-4cca-bb81-be591c0b695e` - Shant Chinchinian (Jinjinian)

### Removed
- `103873ce-6f60-4f75-8628-ec46aad72144` - Michel Helou
- `e6781850-b7b0-48ed-80d5-3ba42f15da07` - Shant Chinchinian / Jinjinian
- `c54e6db7-0f4c-4073-afd9-79809724b184` - Ibrahim Najjar
- `ed00b520-4d08-4071-93f0-3fba0b94867f` - Sleiman Frangieh

## Proposed Solution

The first two just need re-mapped. The following two need investigated as to why they're vanishing, and reinstated.

## Related Issues

* https://github.com/everypolitician/everypolitician-data/pull/14062

**Comment by wfdd** [comment]
You can find the official list [here](https://www.lp.gov.lb/HouseDetails.aspx?id=1), though you might need someone who speaks Arabic to make sense of it.  'Sleiman Frangieh' was a duplicate/misspelling of S*u*leiman, `ddf6a782-dfa0-40e6-af1d-2896c55a7f0d`.  Ibrahim Najjar was apparently mixed up with Mohammed el Hajjar in https://en.wikipedia.org/w/index.php?title=Members_of_the_2009%E2%80%9317_Lebanese_Parliament&diff=next&oldid=544725847, restored in https://en.wikipedia.org/w/index.php?title=Members_of_the_2009%E2%80%9317_Lebanese_Parliament&diff=next&oldid=699445329.  The former is definitely not a Sunni.

**Comment by tmtmtmtm** [comment]
fixed in https://github.com/everypolitician/everypolitician-data/pull/15255
