### ISSUE TITLE
Solomon Islands

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#141]
http://www.parliament.gov.sb/index.php?q=node/134 (10 terms)

**Comment by tmtmtmtm** [comment]
No parties listed on main pages, but a list of members by party is at http://www.parliament.gov.sb/index.php?q=node/147

**Comment by tmtmtmtm** [comment]
The list of members by party only includes historic members — not the current ones. @rubeenam, can you see if you can find party memberships somewhere?

**Comment by rubeenam** [comment]
Sure, I am looking!

**Comment by rubeenam** [comment]
MPs from 2014 general elections, parties and constituencies

http://www.siec.gov.sb/index.php/journalist/127-2014-national-general-election-results

**Comment by tmtmtmtm** [comment]
Excellent, thanks! I'll try merging that in later today.
