### ISSUE TITLE
Iran (Majles) 10th term end_date not being parsed (Parsi date)

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/everypolitician-data#14256]
# Problem with Existing Data

## Legislature

Iran (Majles)

## Problem

The incoming data has `end_date` in Iranian date format, which we're not parsing. As a result politicians who we know are no longer serving have no `end_date` so appear in the data.

## Proposed Solution

Maybe use https://github.com/hzamani/parsi-date to handle the date: this in turn might mean we need to add a scraper to do this because we're currently pulling data straight out of Google spreadsheet.

## Notes

Related to https://github.com/everypolitician/everypolitician-data/pull/13594 which is putting the original data in.

**Comment by tmtmtmtm** [comment]
@davewhiteland can this be closed now?

**Comment by davewhiteland** [comment]
Yes: this has been fixed by updating the spreadsheet at source (upstream). Now uses YYYY-MM-DD format instead.

Also added underscores to column titles as this was a workaround pending everypolitician/everypolitician#495 being fixed.

There _may_ be a case for parsing Parsi dates in general, but as we don't have a use-case for it right now (that is: elsewhere we might be handling this at the scraper level, so all the dates coming into EveryPolitician are already being converted), I won't open an issue for that. We can do so if it because a problem.
