### ISSUE TITLE
Broken Import: Venezuela

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#15404]
## Legislature

Venezuela — National Assembly

## Problem

Losing wikidata for Q12201253 (Ricardo Antonio Molina Peñaloza)

**Comment by octopusinvitro** [comment]
Closed as the problem was solved in https://github.com/everypolitician-scrapers/venezuela-asamblea-wikidata/pull/1.

See for example: https://github.com/everypolitician/everypolitician-data/pull/16297
