### ISSUE TITLE
Papua New Guinea

### ISSUE THREAD

**Issue by duncanparkes** [everypolitician/everypolitician-data#159]
Nested menu's reveal constituencies and regions - we'll have to parse the details pages to get anything else useful.

http://www.parliament.gov.pg/

**Comment by duncanparkes** [comment]
Scraper here - can't get it on Morph yet, as morph is having a bad day.

https://github.com/duncanparkes/papuanewguinea

**Comment by tmtmtmtm** [comment]
Great.

In:
    {'id': 2012, 'name': '2012-1017', 'start_date': '2012', 'end_date': 2017},

I assume that's meant to be 2017, rather than 1017…

(interesting mix of strings and integers there too!)

**Comment by tmtmtmtm** [comment]
I'm guessing that https://github.com/duncanparkes/papuanewguinea/commit/a8c3bfb89c48ff2b7b7e67df8e644f8e74414d80 means this is now ready to go once Morph is working?

**Comment by duncanparkes** [comment]
Scraper here: https://morph.io/duncanparkes/papuanewguinea

I believe this contains everything you need.

**Comment by tmtmtmtm** [comment]
* An `id` column would be strongly preferred
* The party data needs to be cleaned up — at the minute there are separate entries for "People's National Congress", "People's National Congress (P.N.C)", "People's National Congress (PNC)", "People's National Congress (P.N.C.)", "People's National Congress (P.NC)", "People's National Congress (P.NC.)", "Peoples National Congress (P.N.C)", etc 
* At the moment there are 4 different geographic fields (`province`, `region`, `area`, `district`) — how does these inter-relate, or what should we be doing with any of them?

**Comment by duncanparkes** [comment]
1) `id` column - I can see nothing useful to base an id column from. Given that you will make up an `id` yourself, I can't see any point in me making code to make one up too.

2) I've cleaned up the party data as of https://github.com/duncanparkes/papuanewguinea/commit/59780481a138eb3de8c3d8635b2b9a3ace006301

I'm sure there is more that could be done there - there always is.

3) Use 'area'. Province/Region/District are hierarchical, with the smallest which is on a record being the thing I think you should use, this is what is copied to 'area'.

**Comment by tmtmtmtm** [comment]
If I have to make an ID it will be different every time we re-run the scraper, which spews out needless diffs. If you make one, it can be consistent.

**Comment by tmtmtmtm** [comment]
The first entry in the morph database here is "Position is Vacant", which isn't a person. As discussed earlier, if you want to capture empty seats, you should write them to a different table.

**Comment by duncanparkes** [comment]
OK - I'll see what I can do then.

**Comment by duncanparkes** [comment]
Ah ok - that's because I haven't emptied the table - the code to ignore it is there.

**Comment by duncanparkes** [comment]
I think you're wrong about that actually, but I'm off this after today, so I leave it up to you!

**Comment by tmtmtmtm** [comment]
> I think you're wrong about that actually,

What does the 'that' refer to here?

**Comment by duncanparkes** [comment]
About not putting the currently empty constituencies in the main CSV. If I were collating something like this manually in a CSV file I might well start with a list of constituencies and then fill the details in. I certainly would in the UK after an election.

**Comment by duncanparkes** [comment]
Adding an extra constituencies table is exactly the kind of thing we were trying to avoid.

**Comment by tmtmtmtm** [comment]
Our workflow assumes that a Morph `data` table is a list of _people_, and all the tools we've built so far for working with it expects every entry in it to be a legislator. 

Making *this* scraper output a table of _constituencies_ instead, some of which have information about people, and some of which don't, may potentially be of use in some other context, but would require us to add unique special-case handling for it, introducing significant upstream complexity for close to zero additional benefit. 

If you want to capture information for future use that our existing toolchain doesn't currently handle, then that's fine — but that should really be stored separately. A `constituencies` table seems to be in keeping with the existing handling of separate tables for, e.g. `terms`, but I'm certainly open to alternative suggestions.

**Comment by duncanparkes** [comment]
Presumably the morph workflow is still fairly similar to the CSV workflow? I can certainly normalize, but I thought we specifically wanted not to make other people do that. For now, I'm just going to skip that row.

**Comment by tmtmtmtm** [comment]
If people are giving us the simple person+party+constituency+extras version, then, sure. But that relies on every record following that basic pattern. The basic premise of that approach was that it explicitly wouldn't try to cope with every scenario — and an empty seat is a good example of something that it isn't set up to cope with, and where the extra complexity of making it do doesn't seem worth it. Once we're into capturing data that doesn't follow the simplified format, then we should throw it in different files — like we're doing with terms, seat counts, etc — rather than stretching the simple version too far.

**Comment by duncanparkes** [comment]
As of bea99cd10d9ea0c0d6c06213772e210382a50182, there are some IDs based on slugified names.

**Comment by duncanparkes** [comment]
I think that's everything you need, as long as you're happy with the areas situation.

**Comment by tmtmtmtm** [comment]
That's staged at https://everypolitician-viewer-pr-247.herokuapp.com/papua_new_guinea/term_table/2012.html

I'm a little concerned that the Party information differs so radically from the election results:
  https://web.archive.org/web/20140316232847/http://www.pngec.gov.pg/

**Comment by duncanparkes** [comment]
Wikipedia suggests some party merging etc after the elections.

**Comment by tmtmtmtm** [comment]
Link?

**Comment by tmtmtmtm** [comment]
Closed by #214
