### ISSUE TITLE
UK data has dependency on PopIt

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#16236]
# Problem with Existing Data

## Legislature

UK Commons

## Problem

Lots of data came via YourNextMP, which means we have lots of image links pointing at the original underlying PopIt (e.g. http://yournextmp.popit.mysociety.org/persons/4119/image/5525fb6d413cb4432adffa87)

This is going to go away soon, so we need to either drop these or (preferably) get them from elsewhere.

**Comment by mhl** [comment]
I've made a mapping from old to new image URLs for these files - this gist has the script to do that and the CSV output from it, as of today: https://gist.github.com/mhl/85eddca27b170594ce1f422437c3e914

**Comment by mhl** [comment]
@tmtmtmtm pointed out that it might be better to just switch from `data/UK/Commons/sources/YNMP/winners.csv` to an up-to-date upstream source. That would be https://candidates.democracyclub.org.uk/media/candidates-elected-2015.csv

**Comment by mhl** [comment]
I put a scraper on morph to transform that results file (`candidates-elected-2015.csv`) into a CSV file with the same column headings as the old `winners.csv` in everypolitician-data - that's here: https://morph.io/mhl/uk-ynmp-2015-winners
