### ISSUE TITLE
Broken Import: Poland/Sejm

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#16404]
## Legislature

Poland/Sejm
## Problem

Lots of Wikidata going missing

**Comment by octopusinvitro** [comment]
Looks like the problem is back in #16675, although it was marked as solved in the [TODO](https://github.com/everypolitician/everypolitician/issues/496) list.

Unckecking the TODO checkbox until the problem is solved.

**Comment by octopusinvitro** [comment]
Looks like the problem is back in #16675, although it was marked as solved in the [TODO](https://github.com/everypolitician/everypolitician/issues/496) list.

Unckecking the TODO checkbox until the problem is solved.
