### ISSUE TITLE
Broken Import: India

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#16428]
## Legislature

India/Lok Sabha

## Problem

Wikidata going missing - https://github.com/everypolitician/everypolitician-data/issues/16407

**Comment by chrismytton** [comment]
Looks like this was a transient issue and has fixed itself. https://github.com/everypolitician/everypolitician-data/pull/18351 is the most recent pull request and that isn't missing any Wikidata info.
