### ISSUE TITLE
St. Vincent and the Grenadines

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#178]
http://www.assembly.gov.vc/index.php?option=com_content&view=article&id=28&Itemid=41

includes 6 appointed Senators (http://www.assembly.gov.vc/index.php/senators)

**Comment by rubeenam** [comment]
Headshots of members: http://www.assembly.gov.vc/index.php?option=com_content&view=article&id=34:head-shots&catid=4:photo-gallery&Itemid=49

There is only information about name and constituency in the above links but party association is disclosed here: http://www.assembly.gov.vc/index.php?option=com_content&view=article&id=21&Itemid=33

**Comment by tmtmtmtm** [comment]
Also at http://www.caribbeanelections.com/vc/default.asp
