### ISSUE TITLE
organization_id for posts in Kenya National Assembly is incorrect

### ISSUE THREAD

**Issue by struan** [everypolitician/everypolitician-data#18412]
## Legislature

Kenya National Assembly

## Problem

organization_id for posts is incorrect

## Proposed Solution

At the moment organization_id in the posts section is "legislature" but the id of the National Assembly elsewhere in the data is "574eff8e-8171-4f2b-8279-60ed8dec1a2a". Whatever generates the posts data presumably needs updated.

**Comment by struan** [comment]
There is also a similar problem with the Uganda data.

**Comment by tmtmtmtm** [comment]
Ooh, good catch. Fixed in https://github.com/everypolitician/everypolitician-data/pull/18413
