### ISSUE TITLE
Sierra Leone: images are broken (escaped chars in URL)

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/everypolitician-data#18587]
# Problem with Existing Data

## Legislature

Sierra Leone Parliament
http://everypolitician.org/sierra-leone/parliament/term-table/2-4.html

## Problem

Images are being captured from the official source but are not being displayed on the EP webpage: looks like it may be a problem with the spaces being double-escaped.

## Proposed Solution

Fix the escaping problems so that the images are displayed properly.

## Notes

@davewhiteland is focussing on this legislature right now so would appreciate the fix promptly :-)

**Comment by tmtmtmtm** [comment]
This isn't a problem with the EP webpage. It's a problem with the data in the Popolo:

e.g.


```json
      "image": "http://www.parliament.gov.sl/dnn5/Portals/0/2014%2520DOCUMENT/MPS%2520PICTURES/HON%2520AaronARUNA%2520KOROMA%2520%2520CONST%2520062%2520TONKOLILI%2520DISTRICT%2520NORTHERN%2520REGION%2520APC8.JPG",
```
