### ISSUE TITLE
Estonia Riigikgu -- 2015 term needs archiving

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#20493]
# Site has not been archived

The source URL specified in the scraper is receiving a 301.

## Legislature

Estonia, Riigikogu

## Scraper

https://github.com/everypolitician-scrapers/riigikogu-members-2015

## Source

http://www.riigikogu.ee/?id=31555&op2=print

## Proposed Solution

The site will need to be archived from a cache, if available.

**Comment by ondenman** [comment]
@tmtmtmtm I might have opened this issue prematurely. Is https://github.com/everypolitician-scrapers/estonia-riigikogu addressing this issue?

**Comment by tmtmtmtm** [comment]
@ondenman why are you working with this scraper? I can't see it listed in https://github.com/everypolitician/everypolitician-data/blob/a75baf71ca1279c588adc2534a29f82c40dc1820/data/Estonia/Riigikogu/sources/instructions.json

**Comment by ondenman** [comment]
Closing as irrelevant.
