### ISSUE TITLE
Countries on fire (forthcoming elections soon and must be archived)

### ISSUE THREAD

**Issue by octopusinvitro** [everypolitician/everypolitician-data#20544]
* [ ] 2016-10-23 :-1: **Lithuania** - scraper is failing, site is down.
* [x] 2016-10-23 :+1: **Somalia** - scraper seems to be running daily, site is [a parliament site](http://www.parliament.somaligov.net/The%20Members.html) It's using the archiver already 
* [x] 2016-10-29 :smile: **Iceland** - Archived, the source is GitHub.
* [ ] 2016-10-30 :+1: **Georgia** - [PR already](https://github.com/everypolitician-scrapers/georgia-chemiparlamenti/pull/2) Only one scraper, running daily on morph, page is a parliament page [which seems to have still the old members](http://www.chemiparlamenti.ge/en/who/unit/parliament/)
* [ ] 2016-11-01 :+1: **Palau** - [PR already](https://github.com/everypolitician-scrapers/palau-2012-election/pull/1) scraper ran one year ago with no errors, page [seems that it could dissapear](http://www.oceaniatv.net/republic-of-palau-2012-elections-candidates/)
* [ ] 2016-11-06 :thinking: **Nicaragua** - scraper runs daily, [scraped page is saved in a `page.html` on disk already](https://github.com/everypolitician-scrapers/nicaragua-asamblea/blob/master/page.html) but might be an old version of the page.
* [x] 2016-11-08 :smile: **US** - Uses GitHub as source so it's "archived" [House](https://github.com/everypolitician/everypolitician-data/blob/master/data/United_States_of_America/House/sources/instructions.json#L10) - [Senate](https://github.com/everypolitician/everypolitician-data/blob/master/data/United_States_of_America/Senate/sources/instructions.json#L10)
* [ ] 2016-11-20 :+1:  **San Marino** - [PR already](https://github.com/everypolitician-scrapers/san_marino_council/pull/1)
* [ ] 2016-11-20 :+1:  👀  **Haiti** - scraper ran a year ago with no errors. [Page seems dissapearable](http://www.haiti-reference.com/politique/legislatif/49eme_legis.php)
* [ ] 2016-11-26 **Kuwait** - scraper has been failing since 8 months ago, but scraped page [seems to be working](http://www.kna.kw/clt/erun.asp?id=1979#sthash.EajvWkZ5.dpbs)
* [x] 😄  **[Ghana](https://github.com/everypolitician-scrapers/ghana-parliament/pull/1)** (Oliver)
* [x] **[Gabon](https://github.com/everypolitician-scrapers/gabon-deputes/pull/1)** (Oliver)
* [ ] 👀  **[Macedonia](https://github.com/everypolitician-scrapers/macedonia-sobranie/pull/2)** (Oliver)
* [ ] 🚧 **Bulgaria** (Oliver)
* [ ] 👀  **[Georgia](https://github.com/everypolitician-scrapers/georgia-chemiparlamenti/pull/1)** (Unclear whether site is up to date but needs archiving anyway)
* [ ] :eyes: [Puerto Rico](https://github.com/everypolitician-scrapers/puerto-rico-representantes/pull/1)
* [ ] 🚧 Morocco -- failing part way through with 503 -- will restart tomorrow
* [ ] :eyes: [Oman](https://github.com/everypolitician-scrapers/oman-majlis/pull/1/commits)

__These countries are also listed on the dashboard as having an upcoming election:__
* [x] :smiley:  Côte d'Ivoire (2011 results are in forum post. There is no need to archive as the scraper scrapes from copy of fully rendered page in repo!)
* [x] :smiley: Romania - Archived already!
* [ ] Congo-Kinshasa (DRC) (Source is CSV file)
* [ ] 👀  [Suriname](https://github.com/everypolitician-scrapers/suriname-nationale-assemblee/pull/1)

__Elections in 2017 as listed on Wikipedia's [List of Elections in 2017](https://en.wikipedia.org/wiki/List_of_elections_in_2017)__
* [ ] East Timorese parliamentary election, 2017
* [ ] Malaysian general election, 2017
* [ ] Thai parliamentary election, 2017
* [ ] Albanian parliamentary election, 2017
* [ ] Albanian parliamentary election, 2017
* [ ] Czech parliamentary election, 2017
* [ ] French legislative election, 2017
* [ ] German parliamentary election, 2017
* [ ] :eyes: [Liechtensteiner parliamentary election, 2017](https://github.com/everypolitician-scrapers/liechtenstein-landtag/pull/1)
* [ ] Netherlands general election, 2017
* [ ] Norwegian parliamentary election, 2017
* [ ] Lebanese general election, 2017
* [ ] Bahamian general election, 2017
* [ ] Honduran general election, 2017
* [ ] :eyes: [Micronesian legislative election, 2017](https://github.com/everypolitician-scrapers/micronesia-congress/pull/1)
* [x] New Zealand general election, 2017 (Already archiving)
* [ ] :eyes: [Niuean general election, 2017](https://github.com/everypolitician-scrapers/niue-assembly/pull/1)
* [ ] Papua New Guinean general election, 2017
* [ ] Argentine legislative election, 2017
* [ ] Chilean general election, 2017
* [ ] Ecuadorian general election, 2017
* [ ] Falkland Islands general election, 2017

**Comment by octopusinvitro** [comment]
I'm linking to this list in every PR.

**Comment by davewhiteland** [comment]
Before worrying about elections coming _next year_, make sure we've archived any sites that are still showing old terms for elections that have already happened!  (Such countries are likely to include those we were trying to capture in time for Mozfest, for example).

**Comment by octopusinvitro** [comment]
Who added that section?
