### ISSUE TITLE
Mali

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#206]
Official site: http://assemblee-nationale.ml/ — but the list of Deputies is empty

Current Term = 5th Legislature (2014-01-01–) [http://fr.wikipedia.org/w/index.php?title=Assembl%C3%A9e_nationale_(Mali)&oldid=111609725]

**Comment by rubeenam** [comment]
http://psephos.adam-carr.net/countries/m/mali/mali20131.txt
has names of candidates and parties for the 2013 legislative election

http://africanelections.tripod.com/ml.html
more organised with names and parties but has information only till 2007 national assembly election

**Comment by rubeenam** [comment]
http://eisa.org.za/WEP/mali2013results.htm
candidate name and party for 2013 presidential election

**Comment by tmtmtmtm** [comment]
Yay. The http://psephos.adam-carr.net/countries/m/mali/mali20131.txt one looks like a winner. I don't think it should be too difficult to get the information we need out of that. Thanks!

**Comment by tmtmtmtm** [comment]
Scraper at https://morph.io/tmtmtmtm/mali-psephos
