### ISSUE TITLE
Australia: 37th House of Reps - Peter Duncan has Paul Keating's photo

### ISSUE THREAD

**Issue by treffynnon** [everypolitician/everypolitician-data#23760]
# Problem with Existing Data
## Legislature

Australia: 37th House of Reps - http://everypolitician.org/australia/representatives/term-table/37.html

## Problem

Peter Duncan has been misassigned a photo of former Prime Minister Paul Keating.

![screen shot 2017-01-04 at 14 26 45](https://cloud.githubusercontent.com/assets/65215/21631774/1f1f835c-d28b-11e6-84c0-f06875ca9fc5.png)

As you can see it is Paul Keating's dial in that photo - https://www.google.com/search?site=&tbm=isch&source=hp&biw=1280&bih=708&q=paul+keating&oq=paul+keating&gs_l=img.3..0l10.1350.2659.0.2803.12.9.0.0.0.0.298.967.0j2j2.4.0....0...1ac.1.64.img..8.4.966.fpc9B61lRHc

From the same 37th parly page:

![screen shot 2017-01-04 at 14 38 06](https://cloud.githubusercontent.com/assets/65215/21631823/738cb45a-d28b-11e6-8faf-d18a8067098a.png)

**Comment by tmtmtmtm** [comment]
Thanks @treffynnon — it looks like someone had added that as an image of Peter Duncan on Wikidata, and we picked it up automatically from there. I've removed that on wikidata.org, so the change should flow through into our data soon. I had a quick look for a possible replacement image, but couldn't find one that was either from an official government source or was copyright free. Do you happen to know where we might be able to find one?

**Comment by treffynnon** [comment]
I am afraid not - I don't even know who he is to be honest. I was just
fairly sure he wasn't Keating's clone!

**Comment by tmtmtmtm** [comment]
No worries — thanks for pointing out the problem!
