### ISSUE TITLE
Kosovo (Kuvendit) -- unencoded characters

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#25276]
# Problem with Incoming Data

## Legislature

Kosovo (Kuvendit)

## Problem

Unencoded characters in incoming data.

![screen shot 2017-02-06 at 12 09 59](https://cloud.githubusercontent.com/assets/4107953/22646630/3be94a4c-ec65-11e6-9422-8e3c04bc5199.png)

It looks like we're getting different source pages too for an individual member.

Current: http://www.kuvendikosoves.org/?cid=1,158,753&secid=102&legid=4
Incoming: http://www.kuvendikosoves.org/?cid=1,102,954

# Steps
- [x] Fix scraper to capture legislature name correctly
- [ ] Import data

**Comment by tmtmtmtm** [comment]
Closed by https://github.com/everypolitician/everypolitician-data/pull/31489
