### ISSUE TITLE
Sweden (Riksdag) -- member losing wikidata

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#25278]
# Problem with Incoming Data

## Legislature

Sweden (Riksdag)

## Problem

A member is losing Wikidata and it seems like there are duplicate memberships with differing start and end dates:
```
Sanne Lennström (2014-10-03 - 2017-04-23)
Sanne Lennström (2017-04-24 - 2017-12-31)
Serkan Köse (2014-10-03 - 2017-03-31)
Serkan Köse (2017-04-01 - 2017-08-31)
```

A second wikidata ID is changing but it does not show up in the data when paired to the UUID. The wikidata scraper isn't picking up this entry as the member does not have a wikipedia page.

## Steps

- [x] Refresh data from primary source
- [x] Hardcode wikidata ID into wikidata scraper
- [x] Map UUID to new wikidata ID

**Comment by tmtmtmtm** [comment]
fixed by https://github.com/everypolitician/everypolitician-data/pull/25426
