### ISSUE TITLE
Malta (Parliament) -- disappearing members

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#25279]
# Problem with Incoming Data

## Legislature

Malta (Parliament)

## Problem

Members are being lost from term 12. They are no longer listed on the government site but their URLs are still live. The scraper is being re-written.

Some members are no longer listed. These will have to be scraped separately. Raised in issue: https://github.com/everypolitician/everypolitician-data/issues/24566

## Steps

- [ ] Update scraper.
    - [x] Separate names from prefixes
    - [ ] Capture ceased members with end dates
- [ ]  Import data from updated scraper

**Comment by ondenman** [comment]
Updated check list

**Comment by tmtmtmtm** [comment]
Fixed in https://github.com/everypolitician/everypolitician-data/pull/33837 by scraping this information from Wikidata instead of the official site.
