### ISSUE TITLE
Peru (Congress) -- losing election data

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#25283]
# Problem with Incoming Data

## Legislature

Peru (Congress)

## Problem

Losing general election data.

**Comment by tmtmtmtm** [comment]
This was due to the general election being split into separate legislative + presidential elections. I added a date to the legislative election, and have triggered a rebuild.

**Comment by tmtmtmtm** [comment]
fixed in https://github.com/everypolitician/everypolitician-data/pull/27201
