### ISSUE TITLE
Brazil (Chamber of Deputies)

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#25287]
# Problem with Incoming Data

## Legislature

Brazil (Chamber of Deputies)

## Problem
Member losing wikidata.

## Steps
- [x] Refresh from primary source (https://github.com/everypolitician/everypolitician-data/pull/25342)
- [x] Fix link to incorrect wikidata page upstream (The member was losing wikidata because the Wikipedia source list was linking to a disambiguation page.)
- [x] Refresh wikidata

**Comment by tmtmtmtm** [comment]
Closed by https://github.com/everypolitician/everypolitician-data/pull/25424
