### ISSUE TITLE
Netherlands (Tweede Kamer) -- broken import

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#25284]
# Problem with Incoming Data

## Legislature

Netherlands (Tweede Kamer)

## Problem

Member start date changing.

It appears that the member took pregnancy leave. The new start date marks the date of her return.

https://en.wikipedia.org/wiki/Lea_Bouwmeester

![screen shot 2017-02-13 at 09 33 22](https://cloud.githubusercontent.com/assets/4107953/22877911/7ee1c5a8-f1cf-11e6-8a97-ddb2f5df81f9.png)

**Comment by tmtmtmtm** [comment]
Closed in https://github.com/everypolitician/everypolitician-data/pull/25698/files
