### ISSUE TITLE
Afghanistan (Wolesi Jirga): multiple changes

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#25285]
# Problem with Incoming Data

## Legislature

Afghanistan (Wolesi Jirga)

## Problem
Lots of membership changes and new members.

**Comment by ondenman** [comment]
Lots of members being removed. Though it looks like many of the removed names are malformed.

![screen shot 2017-02-24 at 12 00 01](https://cloud.githubusercontent.com/assets/4107953/23302901/dcd4e44e-fa88-11e6-802b-edbc379ef08b.png)

**Comment by ondenman** [comment]
Member is has prefix attached to name:
![screen shot 2017-02-28 at 16 49 43](https://cloud.githubusercontent.com/assets/4107953/23415093/05e09662-fdd6-11e6-893b-997b29e9d738.png)

UUID changing:
![screen shot 2017-02-28 at 16 51 20](https://cloud.githubusercontent.com/assets/4107953/23415138/2b6fb516-fdd6-11e6-9cd3-ca717e7e5ef8.png)

**Comment by ondenman** [comment]
The latest import is adding rows only. No members are being removed.

**Comment by tmtmtmtm** [comment]
closedin https://github.com/everypolitician/everypolitician-data/pull/31463#pullrequestreview-31522598
