### ISSUE TITLE
Guyana: broken import -- missing member

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#25298]
# Problem with Incoming Data

## Legislature
Guyana (National Assembly)

## Problem
~Images coming in with relative URLs. Also, some members are coming in with placeholder images:~

![screen shot 2017-01-30 at 11 45 03](https://cloud.githubusercontent.com/assets/4107953/22424271/bf147f4a-e6ed-11e6-8d9a-91e111a8224a.png)

The relative URL problem doesn't seem to be occurring in the latest PR. We are, however, losing a member.

Incoming data contains 'new' members.

## Steps

- [ ] Rewrite scraper to capture absolute urls
…
- [ ] Import data

**Comment by ondenman** [comment]
Updated description.

**Comment by ondenman** [comment]
Incoming data is adding members and removing one member.

**Comment by tmtmtmtm** [comment]
Fixed in https://github.com/everypolitician/everypolitician-data/pull/31888
