### ISSUE TITLE
Kenya: broken import (vanishing members)

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#25296]
# Problem with Incoming Data

## Legislature
Kenya (National Assembly)

## Problem
Lots of members being removed.

**Comment by tmtmtmtm** [comment]
resolved (by itself?) in https://github.com/everypolitician/everypolitician-data/pull/25814

**Comment by tmtmtmtm** [comment]
Looks like https://morph.io/tmtmtmtm/kenya-mzalendo ran to completion this time. I suspect we'll be re-opening this though…

**Comment by tmtmtmtm** [comment]
This is happening again; as the scraper seems to struggle, I'm going to turn off `scraped_page_archive` to see if it helps.
