### ISSUE TITLE
Nigeria (Representatives and Senate): use term numbers, not years

### ISSUE THREAD

**Issue by mhl** [everypolitician/everypolitician-data#25305]
# Problem with Existing Data

## Legislature

The House of Representatives and (soon) the Senate of Nigeria.

## Problem

The ID for the term of the National Assembly of Nigeria that we currently have is `2015`, but @tmtmtmtm pointed out that the National Assembly does actually number terms - the 2015 is the 8th.

## Proposed Solution

We should change the ID used in `data/Nigeria/Senate/sources/manual/terms.csv` to use the number of the assembly instead of the year.

## Notes

At the time of writing this issue, the senate hadn't yet been added, but we anticipate doing that soon.

**Comment by tmtmtmtm** [comment]
Closed by https://github.com/everypolitician/everypolitician-data/pull/25963
