### ISSUE TITLE
Tonga (Legislative Assembly)

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#25303]
# Problem with Incoming Data

## Legislature
Tonga (Legislative Assembly)

## Problem
Member being added and removed. Lots of membership changes.

**Comment by chrismytton** [comment]
I've migrated the [original Python scraper](https://github.com/duncanparkes/tonga/blob/master/scraper.py) over to Scraped. You can see the current WIP version over in https://github.com/everypolitician-scrapers/tonga-legislative-assembly/pull/1.

**Comment by tmtmtmtm** [comment]
Closed by https://github.com/everypolitician/everypolitician-data/pull/34824
