### ISSUE TITLE
South Korea -- membership changes in term 20 and new party

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#25453]
# Problem with Incoming Data

## Legislature
South Korea (National Assembly)

## Problem
The bot is reporting lots of changes in term 20

**Comment by ondenman** [comment]
Looks like party changes.

**Comment by tmtmtmtm** [comment]
The main problem here was the three vanishing memberships. I've fixed those in https://github.com/everypolitician/everypolitician-data/pull/33735, as well as re-reconciling one of the new members, who was previously in term 19 as well.
