### ISSUE TITLE
Liechtenstein (Landtag): Vanishing member

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#25455]
# Problem with Incoming Data

## Legislature
Liechtenstein (Landtag)

## Problem
Vanishing member

```
Removed
778b1a2d-a54a-4cc2-8723-9d917354c61b - Konzett Bargetze Helen
```

Note:

I moved the scraper in morph but additional changes were coming in. I haven't marked the current PR for review because I think it would be best to deal with the changes from the original scraper URL before changing the source.

(New scraper URL: https://morph.io/everypolitician-scrapers/liechtenstein-landtag)
(Current scraper URL: https://morph.io/tmtmtmtm/liechtenstein-landtag)

**Comment by tmtmtmtm** [comment]
Fixed in https://github.com/everypolitician/everypolitician-data/pull/32092
(I migrated the scraper to use `scraped`, and added ceased members.)
