### ISSUE TITLE
Vietnam (National Assembly): member data changing

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#25513]
# Problem with Incoming Data

## Legislature
Vietnam (National Assembly)

## Problem
The incoming data for one member is being replaced by data for another.
![screen shot 2017-02-10 at 16 49 36](https://cloud.githubusercontent.com/assets/4107953/22835592/301a0ef0-efb1-11e6-8a09-05b64731a4fa.png)
Current member image:
![2828](https://cloud.githubusercontent.com/assets/4107953/22835649/5a04c228-efb1-11e6-99d2-29da372507b7.jpg)
Incoming:
![3032](https://cloud.githubusercontent.com/assets/4107953/22835653/5f5ff2ba-efb1-11e6-843b-c1332db7498f.jpg)

The likely cause is the broken scraper: https://github.com/everypolitician/everypolitician-data/issues/25383

**Comment by ondenman** [comment]
The current PR is also losing wikidata.

**Comment by ondenman** [comment]
Multiple wikidata items have been deleted because: _"Does not meet the notability policy"_

```
Wikidata Changes

4da0da97-d47f-4e66-802d-0021d6d339ba: Q10770547 → none

4e453fb3-c597-49db-9a70-074a54daa2c6: Q10757632 → none

a7049d24-eee7-40eb-9acc-a5d71e74fefb: Q10769161 → none

fcbbfcf9-9225-4caa-8d58-55f1491c1c99: Q10769963 → none
```

**Comment by ondenman** [comment]
There are two members that share the same name. The scraper creates the id from the URL using `File.basename`. But this returns the same result for both despite the URLs being different: `http://dbqh.na.gov.vn/daibieu/23/2828/Nguyen-Ngoc-Bao.aspx` & `http://dbqh.na.gov.vn/daibieu/61/3032/Nguyen-Ngoc-Bao.aspx`

**Comment by tmtmtmtm** [comment]
Member changes fixed in https://github.com/everypolitician/everypolitician-data/pull/31036

(https://github.com/everypolitician/everypolitician-data/issues/25383 is still an issue though)
