### ISSUE TITLE
Bangladesh (Jatiyo Sangshad) -- disappearing membership

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#25700]
# Problem with Incoming Data

## Legislature

Bangladesh (Jatiyo Sangshad)

## Problem
Losing membership from term ten.

```
Removed

term/10

Suranjit Sengupta
```

Although their personal page is still live, the member no longer appears in the source list:
![screen shot 2017-02-16 at 12 04 20](https://cloud.githubusercontent.com/assets/4107953/23020699/2f26773e-f440-11e6-8920-4d253fed90b3.png)

## Steps
- Update scraper.
    - [ ] Add test framework
    - [ ] Set up check-fail
    - [ ] Move classes to separate files
    - [ ] Add MemberPage class
    - [ ] Import data
    - [ ] Capture missing member (hardcode url in scraper)
    - [ ] Import data

**Comment by ondenman** [comment]
Member's page still exists.

**Comment by ondenman** [comment]
Looks like we're losing two memberships now:
![screen shot 2017-04-04 at 10 54 41](https://cloud.githubusercontent.com/assets/4107953/24651281/2aeb8cfe-1925-11e7-98eb-1c0b1117155a.png)

**Comment by tmtmtmtm** [comment]
Fixed in https://github.com/everypolitician/everypolitician-data/pull/31903

(Suranjit Sengupta died in February)
