### ISSUE TITLE
Brazil (Chamber of Deputies) -- losing data

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#25921]
# Problem with Incoming Data

## Legislature
Brazil (Chamber of Deputies)

## Problem
Losts of data being lost from term 55 source.

**Comment by ondenman** [comment]
Some member email addresses are changing.
![screen shot 2017-02-24 at 10 55 25](https://cloud.githubusercontent.com/assets/4107953/23300964/e5726b02-fa7f-11e6-9ab1-a14a0870160e.png)

Other members are losing addresses:
![screen shot 2017-02-24 at 10 56 43](https://cloud.githubusercontent.com/assets/4107953/23300994/fccec1ce-fa7f-11e6-9cf6-b8cd0d68bd7a.png)

**Comment by ondenman** [comment]
Lots of members losing contact details:
![screen shot 2017-02-28 at 16 30 53](https://cloud.githubusercontent.com/assets/4107953/23414293/528b67ce-fdd3-11e6-9234-6d36146957e5.png)

**Comment by tmtmtmtm** [comment]
Closed in https://github.com/everypolitician/everypolitician-data/pull/31490
