### ISSUE TITLE
Belize (House of Representatives) -- new member

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#26284]
# Problem with Incoming Data

## Legislature

Belize (House of Representatives)

## Problem
New member data.

## Steps
- [ ] Handle name prefix in scraper.

**Comment by ondenman** [comment]
Incoming member is speaking. 'Mrs.' is attached to the member's name.

**Comment by tmtmtmtm** [comment]
closed in https://github.com/everypolitician/everypolitician-data/pull/32325 (we can remove the prefixes separately)
