### ISSUE TITLE
Poland (Sejm)

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#26281]
# Problem with Incoming Data

## Legislature

Poland (Sejm)

## Problem
Member losing wikidata

## Steps
- [ ] Pair new upstream id with original UUID

**Comment by ondenman** [comment]
Term 4 member has a new upstream id:
![screen shot 2017-02-28 at 15 31 32](https://cloud.githubusercontent.com/assets/4107953/23411721/18e48008-fdcb-11e6-895d-65ed9a28e842.png)

Party data for three term 8 members is changing.

**Comment by tmtmtmtm** [comment]
Fixed in https://github.com/everypolitician/everypolitician-data/pull/27119
