### ISSUE TITLE
Ukraine  (Verkhovna Rada) -- members losing wikidata

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#27028]
# Problem with Incoming Data

## Legislature
Ukraine (Verkhovna Rada)

## Problem
Members losing wikidata. It appears that some wikidata articles have been moved.

##Steps
- [ ] Pair UUIDs with new wikidata ids.

**Comment by ondenman** [comment]
The wikidata id for one member has changed.

**Comment by tmtmtmtm** [comment]
Fixed in https://github.com/everypolitician/everypolitician-data/pull/27189
