### ISSUE TITLE
North Korea (Supreme People’s Assembly) -- member losing wikidata

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#27031]
# Problem with Incoming Data

## Legislature
North Korea (Supreme People’s Assembly)

## Problem
Members losing wikidata

## Steps
- [ ] Pair member UUID with new wikidata id

**Comment by tmtmtmtm** [comment]
Two wikidata pages for Jo/Cho Yon-jun were merged, but English Wikipedia was still pointing at Q25753004 (the old, redirected item) rather than Q11727287. Deleting and reinstating the link on Wikidata sorted it out.

**Comment by tmtmtmtm** [comment]
fixed in https://github.com/everypolitician/everypolitician-data/pull/27175/
