### ISSUE TITLE
Bolivia (Chamber of Deputies)

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#27044]
# Problem with Incoming Data

## Legislature
Bolivia (Chamber of Deputies)

## Problem
New members coming in. Existing member changing UUIDs

## Steps
- [ ] Pair new upstream id with existing UUID

**Comment by tmtmtmtm** [comment]
Closed by https://github.com/everypolitician/everypolitician-data/pull/26697
