### ISSUE TITLE
Argentina (Cámara de Diputados):

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#27042]
# Problem with Incoming Data

## Legislature
Argentina (Cámara de Diputados)

## Problem
New data coming in but no changes.

**Comment by tmtmtmtm** [comment]
@ondenman not sure why you think there are no changes — there are two new people, with new memberships. The issue here is that they need to be reconciled.

**Comment by ondenman** [comment]
This issue is now part of: https://github.com/everypolitician/everypolitician-data/issues/25456

**Comment by caras-art** [comment]
> # ACTIVE Incoming Data&REAL TIME 
> ## Legislature
> MEXICO ENSENADA (Cámara de Diputados)
> ARTURO ALBERTO ORTIZ RODRIGUEZ 
> ## ACTIVE
> New data coming IN ONchanges.
