### ISSUE TITLE
Mauritius

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#276]
http://mauritiusassembly.govmu.org/English/hmembers/Pages/default.aspx

Many have only names — no parties or constituencies

**Comment by rubeenam** [comment]
http://electoral.govmu.org/English/electionresult/nasselec/Pages/Detailed-Results-by-Constituency-2014.aspx

Candidate name, party and constituency information for 2014 National Assembly Election

**Comment by tmtmtmtm** [comment]
Nice find — though getting data out of PDFs is always quite tricky (doubly so when key information comes down to purely a matter of formatting — the candidates who were elected being in bold — but that might not really matter as we can just cross match the names). If you could find a version that wasn't PDF that would be much better, but if not, I'll have a look at running this through some of the pdf-to-text conversion tools and see what we get. 

It might turn out to be one that's just as quick to do manually, though.

**Comment by rubeenam** [comment]
same result in a non-pdf format here. lists only elected candidates of every constituency 
http://www.maurinet.com/about_mauritius/election_results_2014

**Comment by tmtmtmtm** [comment]
Oh, excellent. It's non-trivial to actually parse, but it should be a lot easier than the PDFs. Thanks!

**Comment by tmtmtmtm** [comment]
http://www.lexpress.mu/resultats looks like an easier version to handle

**Comment by tmtmtmtm** [comment]
Scraper at https://morph.io/tmtmtmtm/mauritius-election-2014
