### ISSUE TITLE
Gibraltar

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#284]
http://www.parliament.gi/history/composition-of-parliament — lists everyone back to the First House of Assembly in 1969

Looks quite awkward to scrape though — would likely be much easier done by making a spreadsheet by hand.

**Comment by rubeenam** [comment]
http://www.snipview.com/q/Gibraltarian_politicians_by_party

list of political parties with members and their info

**Comment by andylolz** [comment]
Initial attempt at scraping this here:
https://morph.io/andylolz/gibraltar-parliament

I’ll have a go at improving it this weekend.

**Comment by tmtmtmtm** [comment]
Yay! Thanks @andylolz 

it would be super-useful if you could create a `terms` table as well with `id`, `name`, `start_date`, and `end_date`: eg "1,First House of Assembly,1969,1972"

**Comment by andylolz** [comment]
Gotcha, will do. This is a very initial attempt at the moment – I’ll also check field names etc against some other scrapers to get an idea of how it should be done!

**Comment by tmtmtmtm** [comment]
Great. There's some documentation at http://everypolitician.org/scrapers.html and http://everypolitician.org/submitting.html, but looking at other examples is good too, as there's probably things we've left out of that!

**Comment by andylolz** [comment]
Ahh – really useful, thanks!
