### ISSUE TITLE
Wallis and Futuna (Territorial Assembly) -- Incoming data broken

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#28726]
# Problem with Incoming Data

## Legislature
Wallis and Futuna (Territorial Assembly)

## Problem
Incoming data is broken. Possibly caused by a change in the source layout.

![screen shot 2017-03-20 at 10 58 42](https://cloud.githubusercontent.com/assets/4107953/24097114/5efa46cc-0d5c-11e7-8375-d0fd0665222a.png)

**Comment by tmtmtmtm** [comment]
Fixed in https://github.com/everypolitician-scrapers/wallis-and-futuna-territorial-assembly/commit/56659ffdc8c4d3b5194f5c5c1555b434c6fc980b
