### ISSUE TITLE
Cote D'Ivoire

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#293]
Site was: http://www.anci.ci/
Site now: http://www.assnat.ci/assembleenationale/ — but the link to the Deputies does nothing

**Comment by rubeenam** [comment]
http://forums.abidjan.net/elections/legislatives/2011/resultats/resultats.asp

list of elected representatives with images and party names for 2011 election

**Comment by tmtmtmtm** [comment]
Great find! Thanks.

**Comment by rubeenam** [comment]
I think this one has list of all candidates with pictures and biographies
(at the bottom right of the page).

http://forums.abidjan.net/elections/legislatives/2011/index.asp

I will also try to find a non PDF version for results. Thank you!

**Comment by tmtmtmtm** [comment]
Scraper for the election results site: https://morph.io/tmtmtmtm/ivory-coast-election-results-2011

Though it's only finding 242 winners, and https://fr.wikipedia.org/wiki/Assembl%C3%A9e_nationale_(C%C3%B4te_d%27Ivoire) says there should be 255 deputies.

Have you seen anything that suggests the remainder may be, say, presidential appointees, or are reserved for other people who aren't elected in the same manner?

**Comment by tmtmtmtm** [comment]
Data now live at http://data.everypolitician.org/ivory-coast/

**Comment by rubeenam** [comment]
it seems 11 seats were annulled after being challenged in court and
by-election was held for them later.
http://www.news24.com/Africa/News/I-Coast-court-annuls-11-election-results-20120131

But the election was for 255 candidates. I am not sure but this website
might have forgotten to update the information or possibly they just made a
mistake.
