### ISSUE TITLE
Multiple Simultaneous Membership in Welsh Assembly

### ISSUE THREAD

**Issue by ajparsons** [everypolitician/everypolitician-data#30364]
# Problem with Existing Data

If you want to draw attention to a bug in our existing data or something we could improve in it, please fill in the following template:

## Legislature

Welsh Assembly

## Problem

Two people in term/5 switched parties and so have multiple memberships - but these don't have start/end dates - unclear from data which is the 'current' info. 

451236de-0f5e-448b-a11c-7923bd704fb8
1ee666d1-225f-4561-92da-cfcb94b91a6d

## Proposed Solution

Test for overlapping 'member' roles without additional time information.

**Comment by tmtmtmtm** [comment]
@ajparsons can you find anywhere on the official site where dates are given for the switch?

**Comment by ajparsons** [comment]
@tmtmtmtm Closest I have is news stories:

Nathan.Gill - 2016,8,17 - http://www.bbc.co.uk/news/uk-wales-politics-37105782
Dafydd.Elis-Thomas - 2016,10,14 - http://www.bbc.co.uk/news/uk-wales-politics-37661776

**Comment by tmtmtmtm** [comment]
@ajparsons Yeah, it's not too difficult to find them manually, but it would be much better if we didn't have to! (We now have to add Mark Reckless to the list as well…)

**Comment by tmtmtmtm** [comment]
This was fixed by https://github.com/everypolitician/everypolitician-data/pull/99215
