### ISSUE TITLE
Ireland (Dáil Éireann): Party changes

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#30527]
# Problem
Several members have changed parties but the dates of the membership changes are not recorded.

![screen shot 2017-03-30 at 15 56 04](https://cloud.githubusercontent.com/assets/4107953/24510544/6e3e5008-1561-11e7-895c-57a7f3ae4642.png)

Also, the Anti-Austerity Alliance has changed names to Solidarity.

**Comment by tmtmtmtm** [comment]
Fixed in https://github.com/everypolitician/everypolitician-data/pull/30623
