### ISSUE TITLE
Jamaica (House of Representatives): Wikipedia refresh loses member

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#31156]
# Problem with Incoming Data

## Legislature
Jamaica (House of Representatives)

## Problem
A member is disappearing from the wikipedia source.

![screen shot 2017-04-04 at 10 57 46](https://cloud.githubusercontent.com/assets/4107953/24651403/98e3a7e6-1925-11e7-84d8-4085000583f2.png)

**Comment by ondenman** [comment]
Looks like the member is dead. http://www.jamaicaobserver.com/editorial/Dwayne-Vaz-s-loaded-gun_45979

**Comment by tmtmtmtm** [comment]
Closed in https://github.com/everypolitician/everypolitician-data/pull/31470
