### ISSUE TITLE
South Africa: no ID for AIC

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#33261]
Builds for South Africa are failing with

```
Missing organization ID for "African Independent Congress"
```

This seems to be because, [unlike all the other Parties](http://www.pa.org.za/organisation/national-assembly/), there's no bracketed part of their name on People's Assembly, for the scraper to split on.

![screen shot 2017-04-21 at 12 28 07](https://cloud.githubusercontent.com/assets/57483/25275597/04850984-268e-11e7-83d7-9c0cef7bdef4.png)

We could adjust the scraper to hard-code this one, or deduce it from the URL, though I'm wondering if this is just an oversight and could be fixed upstream. (ping @mhl)

**Comment by mhl** [comment]
Sorry I missed this ping. After checking with PMG that it's OK (they assented) I've added the " (AIC)".

**Comment by tmtmtmtm** [comment]
@mhl — that's excellent, thanks!
