### ISSUE TITLE
Antigua and Barbuda 

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#405]
Government website only list names  http://www.ab.gov.ag/article_details.php?id=191&category=66
Basic info available at http://psephos.adam-carr.net/countries/a/antigua/antigua2014.txt

**Comment by tmtmtmtm** [comment]
http://ablp.ag/meet-the-candidates/ looks useful for photos etc too

**Comment by tmtmtmtm** [comment]
* Easier results to scrape: http://www.caribbeanelections.com/ag/results2014.asp or http://www.caribbeanelections.com/blog/?p=4101 
* More details on candidates: http://www.caribbeanelections.com/ag/election2014/candidates/default.asp

**Comment by tmtmtmtm** [comment]
The "Representatives" tab on the constituency pages at http://www.caribbeanelections.com/ag/election2014/constituencies/SJCW.asp etc include details of each MP in that seat since 1971!
