### ISSUE TITLE
Azerbaijan 

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#407]
Only info of 2005 elections in the official website but images and bio available 
http://www.meclis.gov.az/?/en/deputat/Əlifba%20sırası%20üzrə%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0

Basic data from the 2010 election
http://psephos.adam-carr.net/countries/a/azerbaijan/azerbaijan2010.txt

**Comment by tmtmtmtm** [comment]
Is http://meclis.gov.az/?/az/deputat/ not the current list of members?

**Comment by rubeenam** [comment]
If you click this http://www.meclis.gov.az/?/en/deputat/5 (one of the bio of the members in English) it only says about his election in 2005, similar for many other members. That's why suspected it is an older list. The link you send is different than mine? It has info on local language and no detailed bio.

**Comment by rubeenam** [comment]
I have compared the candidates of the offical site with 2010 data from psephos. They match. Although I can't be sure if it is because the same people get elected every time because of the political system or because the result is of 2010 election.
