### ISSUE TITLE
Cook Islands

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#418]
Official website: http://www.parliament.gov.ck/members.html

Only name, party and constituency

**Comment by tmtmtmtm** [comment]
This describes itself as the 2010-2014 members. Is that a correct designation?

**Comment by rubeenam** [comment]
Oh yes, thats's right. Terribly sorry. The results of 2014 are here https://en.m.wikipedia.org/wiki/Cook_Islands_general_election,_2014#Results

Basic info only

**Comment by tmtmtmtm** [comment]
One of these results was a tie, with a complex history of resolution:   
  http://www.cookislandsnews.com/item/50536-mitiaro-saga-long-and-slow-moving/50536-mitiaro-saga-long-and-slow-moving
