### ISSUE TITLE
Moldova: check email addresses

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#4181]
Lots of people seem to have the wrong email addresses in https://github.com/everypolitician/everypolitician-data/blob/04998970d338142b592c2fda363fd78010489134/data/Moldova/Parlamentul/term-2014.csv

* Andrian Candu → Luminita.Bolohan@parlament.md	
* Chiril Lucinschi → Valeriu.Bodiu@parlament.md
* Liliana Palihovici → Alina.Bulgac@parlament.md
* Maria Postoico → Vasile.Esanu@parlament.md
* Marian Lupu → Natalia.Rosca@parlament.md
* Raisa Apolschii → Cristina.Ciolac@parlament.md
* Violeta Ivanov → Svetlana.Stepanov@parlament.md

It's possible that these _are_ the correct addresses, but we should check them to make sure.

**Comment by tmtmtmtm** [comment]
@ondenman can you take this one? In the first instance this is probably just a matter of looking at the official site pages for a handful of these to see whether these actually _are_ the email addresses being used there (in which case there's nothing to do here), or whether we're going wrong somewhere (in which case we need to investigate how/why, and fix it)

**Comment by ondenman** [comment]
Looked at source pages as listed in: https://github.com/everypolitician/everypolitician-data/blob/04998970d338142b592c2fda363fd78010489134/data/Moldova/Parlamentul/sources/morph/data.csv
Email addresses match those listed above. That is, the data matches the site.
