### ISSUE TITLE
Falkland Islands

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#431]
Official website: http://www.falklands.gov.fk/self-governance/legislative/assembly-members/

Basic info plus image and bio of the current parliament members

**Comment by tmtmtmtm** [comment]
According to wikipedia: [As no political parties are active in the Falklands, all the candidates stood as Independents](https://en.wikipedia.org/wiki/Falkland_Islands_general_election,_2013)

**Comment by rubeenam** [comment]
Thank you, similar for Guernsey and added that information in the issue.

**Comment by dracos** [comment]
Back to 1981: https://morph.io/dracos/falkland-islands

**Comment by dracos** [comment]
Have added 1977 too. Before then there were appointed members who aren't listed on Wikipedia, only the elected ones. None of these include the two ex officio members (the Chief Executive and the Director of Finance) or the Speaker, nor the Commander British Forces and the Attorney General. All have the right to take part in proceedings but may not vote.

**Comment by tmtmtmtm** [comment]
Thanks @dracos 

I added another scraper for the official site, so as to get their photos, and another to use your `wikiname` column to look up info on them in Wikidata too (which also prompted me to work out how to fix that process to resolve links to pages that are just Wikipedia-style redirects, yay.)

http://everypolitician.org/falkland-islands/
