### ISSUE TITLE
Guernsey

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#432]
Official website: http://www.gov.gg/states_members

PDF  detailing basic info, image and contact address of Parliament Members (from page 6 to 18)
http://www.gov.gg/CHttpHandler.ashx?id=75142&p=0

There are no political parties in Guernesy and candidates are elected as independents.

**Comment by tmtmtmtm** [comment]
PDFs are nasty. But http://gov.gg/states_members_contact_details gives name, email, linkedin, and constituency information for each of them. 

According to https://en.wikipedia.org/wiki/States_of_Guernsey, all are Independents.

**Comment by tmtmtmtm** [comment]
Scraper at https://morph.io/tmtmtmtm/guernsey-states
