### ISSUE TITLE
New Caledonia

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#433]
Official website: http://www.congres.nc/assemblee/les-elus/?panel=5

Party, Constituency, Image, profile

**Comment by tmtmtmtm** [comment]
Term information: https://fr.wikipedia.org/wiki/Congr%C3%A8s_de_la_Nouvelle-Cal%C3%A9donie#Historique

**Comment by tmtmtmtm** [comment]
* Scraper at https://morph.io/tmtmtmtm/new-caledonia-assemblee
* + Wikidata scraper: https://morph.io/tmtmtmtm/new-caledonia-mps-wp

**Comment by tmtmtmtm** [comment]
Closed by #475 and #476
