### ISSUE TITLE
Hong Kong 

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#434]
Official website: http://www.legco.gov.hk/general/english/members/yr12-16/biographies.htm

Basic info, image, bio, contact information

**Comment by struan** [comment]
I'm looking at this.

**Comment by struan** [comment]
scraper at https://morph.io/struan/hong_kong_legislative_council_members

**Comment by tmtmtmtm** [comment]
Thanks @struan 

* The honorific_prefix detection needs to be a bit smarter though, it's currently splitting off 'Dr' and leaving 'Hon LAU Wong-fat', for example.
* It's not crucial, but if it's as easy as it looks to grab the phone+fax numbers those would be useful too
* Curious as to why you left the 'yr12-16/' in all the IDs…

**Comment by struan** [comment]
Oooh, yes, good point on the honorific thing.

Fixed, plus phone and fax and gender for the single person it can actually get right.

**Comment by tmtmtmtm** [comment]
Thanks @struan: now merged.

I've opened a separate ticket for scraping the Wikipedia/Wikidata info too: #805
