### ISSUE TITLE
Haiti 

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#436]
Official website directs to a random page: http://www.parlementhaitien.ht/

Information on candiates, parties and constituency here: http://www.caribbeanelections.com/knowledge/parliament/ht_parliament/ht_house.asp

The new elections will be held in August 2015, they were slated to be held last January but did not take place.

**Comment by tmtmtmtm** [comment]
Do they even _have_ a Parliament at the moment? It seems that it was dissolved in January.

**Comment by rubeenam** [comment]
This is the list of members before dissolution.
