### ISSUE TITLE
Lithuania

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#442]
http://www3.lrs.lt/pls/inter/w5_show?p_r=8787&p_k=2

Historic terms linked from http://www3.lrs.lt/pls/inter/w5_show?p_r=3804&p_k=2

All look quite easy to scrape, though we should see what work http://manoseimas.lt/ has already done on this before duplicating effort.

**Comment by tmtmtmtm** [comment]
@doublemarked, do you know if there's anything we can reuse (API and/or code) to get the basic information on the membership of the Seimas (names, parties, periods, etc), rather than simply re-scraping it all?

**Comment by doublemarked** [comment]
@tmtmtmtm A pleasure to hear from you, Tony! 

We haven't been active with ManoSeimas lately, but we do have some resources available that should be of help:

1. All of our scraped data is stored in a public CouchDB: http://couchdb.manoseimas.lt/_utils/ ... admittedly, the structure is a bit convoluted, but there's a lot of utility to it. I believe the scraper is still running and has things up to date. Check out the `mps` database, which contains all the MPs with the appropriate sittings, parties, the source URLs, etc etc.

2. The site and scraper code is all open source as well: https://bitbucket.org/manoseimas/manoseimas ... the relevant scraper code is at in `manoseimas/scrapy`

Let me know if this is what you're seeking, and what else I can do to help.

**Comment by tmtmtmtm** [comment]
Hi Heath! Thanks for the pointers. That data looks like just the trick!  It'll probably be next week before I get to dig deeply into it, but I'll give you shout if there's anything I can't work out…

Do you know off-hand how far the data goes back? My CouchDB-fu is pretty weak, so I don't know if there's a trivial way to query that. The official site seems to list all the members since the 1996 term, but I couldn't find anyone in my random sample that went back earlier than a couple of periods ago, and I'm not sure if that's just because I happened to pick the wrong people, or if only the most recent few terms were grabbed.

**Comment by doublemarked** [comment]
Our data goes back to the start of the Fall 2008 term, but the scraper could easily be configured to go back further.

**Comment by doublemarked** [comment]
Here's a simple view I set up for MPs indexed by parliamentary start date, http://couchdb.manoseimas.lt/_utils/database.html?mps/_design/mps-by-start-date/_view/MPs%20by%20start%20date

**Comment by tmtmtmtm** [comment]
Excellent, thanks! Will dig more deeply next week and let you know how I get on.

Don't suppose you happen to know an equivalent source of pre-scraped Ukrainian data…?

**Comment by doublemarked** [comment]
Wish I knew. Let me know if you succeed or fail on Ukrainian data - I'm curious also, and if you can't locate it I can ask a few people when I'm back in Kyiv next week.

**Comment by doublemarked** [comment]
Wait, just remembered :) Chesno has this data, and it seems they have an API - http://www.chesno.org/api/

**Comment by tmtmtmtm** [comment]
Ah, well remembered! That's definitely useful, though it's a little empty — it doesn't even have Party or Area information. The official site seems fairly straightforward, and has historic data back to 1990 (http://w1.c1.rada.gov.ua/pls/site2/p_deputat_list?skl=8), so I might just scrape that. Or Wikipedia looks fairly comprehensive too, e.g. https://uk.wikipedia.org/wiki/%D0%92%D0%B5%D1%80%D1%85%D0%BE%D0%B2%D0%BD%D0%B0_%D0%A0%D0%B0%D0%B4%D0%B0_%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D0%B8_VII_%D1%81%D0%BA%D0%BB%D0%B8%D0%BA%D0%B0%D0%BD%D0%BD%D1%8F#.D0.94.D0.B5.D0.BF.D1.83.D1.82.D0.B0.D1.82.D0.B8 — albeit in slightly different formats for each term.

**Comment by briatte** [comment]
[My own take at Lithuania](https://github.com/briatte/seimas/blob/master/data.r#L124-L238) returned data for years 2004–today (3 legislatures/terms). I can't remember how far you can go back in time.

**Comment by tmtmtmtm** [comment]
@doublemarked — the current term is now live at http://everypolitician.org/lithuania/ (and indeed also at http://www.gender-balance.org/countries/Lithuania). Will look into earlier terms another time. Thanks for your help!

**Comment by doublemarked** [comment]
Looking good, @tmtmtmtm ! :)

**Comment by tmtmtmtm** [comment]
@doublemarked http://couchdb.manoseimas.lt/ is returning a 400 error for every page at the minute — are you still involved with this / know anything about it, or who to ping if not?

**Comment by doublemarked** [comment]
Not involved for a while, and not sure what happened to it. I do know who to contact, though - I'll reach out and get back to you in a bit.

**Comment by tmtmtmtm** [comment]
Thanks!

**Comment by doublemarked** [comment]
Hey @tmtmtmtm - sent you an email connecting you with the project owner. Seems you'll have to negotiate with them fresh access to the data :/ Sorry about that. Though I'm no longer actively involved, please let me know if there's something I can do to support.

**Comment by doublemarked** [comment]
@tmtmtmtm I was told today by one of the managers at TILS that this had been fixed. I checked the URL and it still seems to produce an error. Did you sort out access via another channel? I don't think I was part of your discussion with Ignas after I handed you over to him.

**Comment by tmtmtmtm** [comment]
Hi @doublemarked — I'm on vacation for a few weeks, but I think @jenmysoc and @davewhiteland have been talking to them about this. Otherwise I'll dig into it all when I'm back. Thanks.

**Comment by davewhiteland** [comment]
Yes @doublemarked as @tmtmtmtm says this was down to me, I'll look into this shortly, sorry!
