### ISSUE TITLE
Bulgaria

### ISSUE THREAD

**Issue by briatte** [everypolitician/everypolitician-data#451]
Here's [my own scraper](https://github.com/briatte/bgparl/blob/master/data.r).

Links to MP pages are of the form

http://www.parliament.bg/bg/MP/222

The index is at

http://www.parliament.bg/bg/MP/

**Comment by tmtmtmtm** [comment]
Also in English from http://www.parliament.bg/en/MP/

**Comment by tmtmtmtm** [comment]
And in XML at http://www.parliament.bg/export.php/en/xml/MP/1000 (etc)

**Comment by briatte** [comment]
Damn, I missed the XML version! That might have made things simpler: my scraper collects both Bulgarian and English pages, because they do not show exactly the same information (time in office can only be computed from the Bulgarian pages, IIRC).
