### ISSUE TITLE
Sweden

### ISSUE THREAD

**Issue by briatte** [everypolitician/everypolitician-data#453]
[My scraper](https://github.com/briatte/riksdag/blob/master/data.r) tells me that, until the 2014 election, this link used to work:

http://data.riksdagen.se/Data/Ledamoter/Ledamoter-2010-2014/

You now have to use this search engine:

http://data.riksdagen.se/personlista/?iid=

The open data portal of the Riksdag is pretty easy to process.

**Comment by tmtmtmtm** [comment]
JSON: http://data.riksdagen.se/personlista/?iid=&fnamn=&enamn=&f_ar=&kn=&parti=&valkrets=&rdlstatus=&org=&utformat=json&termlista=

CSV: http://data.riksdagen.se/personlista/?iid=&fnamn=&enamn=&f_ar=&kn=&parti=&valkrets=&rdlstatus=&org=&utformat=csv&termlista=

**Comment by dracos** [comment]
Looking at this now; also Wikipedia lists at https://en.wikipedia.org/wiki/List_of_members_of_the_Riksdag,_2010–14 and https://en.wikipedia.org/wiki/List_of_members_of_the_Riksdag,_2014–18

**Comment by dracos** [comment]
Rather basic, from official JSON, at https://morph.io/dracos/scraper-sweden-riksdagen
