### ISSUE TITLE
Norway

### ISSUE THREAD

**Issue by briatte** [everypolitician/everypolitician-data#454]
[My scraper is there](https://github.com/briatte/stortinget/blob/master/data.r). It covers only private bill sponsors, based on links found in the bills. MP identifiers are letters, which sometimes contain special accents. As [this part](https://github.com/briatte/stortinget/blob/master/data.r#L139-L149) of the scraper tells you, this can create issues.

**Comment by tmtmtmtm** [comment]
I see you actually get credited on their site :)

http://data.stortinget.no/eksempler
