### ISSUE TITLE
Ireland

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#462]
* KildareStreet provides a downloadable CSV: https://www.kildarestreet.com/tds/
* https://en.wikipedia.org/wiki/Members_of_the_31st_D%C3%A1il lists mid-term changes

**Comment by tmtmtmtm** [comment]
Closed by #463

**Comment by briatte** [comment]
Referencing [my own scraper](https://github.com/briatte/oireachtas/blob/master/data.r), which is messier. The only interesting bit converts [constituencies to Wikipedia English handles](https://github.com/briatte/oireachtas/blob/master/data.r#L396-L405) FWIW.
