### ISSUE TITLE
Vatican City

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#468]
Official website: http://www.vaticanstate.va/content/vaticanstate/en/stato-e-governo/struttura-del-governatorato/organigramma/stato-citta-del-vaticano.html

Image and bio of Cardinals appointed by the Pope to the Pontifical Commission (Vatican's legislature) 
At office since 2011

**Comment by tmtmtmtm** [comment]
Wikipedia: https://en.wikipedia.org/wiki/Pontifical_Commission_for_Vatican_City_State
