### ISSUE TITLE
Northern Mariana Islands

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#479]
Official website: http://www.cnmileg.gov.mp/members.asp?secID=1&legsID=19

Imgae, party, constiuency and contact information.

**Comment by tmtmtmtm** [comment]
Previous 18 terms also available at 
* http://www.cnmileg.gov.mp/members.asp?secID=1&legsID=18
...
* http://www.cnmileg.gov.mp/members.asp?secID=1&legsID=1

(though photos only available from 16 onwards)
