### ISSUE TITLE
French Polynesia

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#482]
Official website:  http://www.assemblee.pf/en/

Link to the representatives page: 
http://www.assemblee.pf/en/representants/vos-representants/trouvez-un-representant

Image, party, constituency, contact info and CV

**Comment by tmtmtmtm** [comment]
Lists are dynamically loaded via Javascript, so can hook into separate gender lists:

* http://www.assemblee.pf/_contenu/_pages_jumi/__recherche-rep-en.php?req=SELECT%20representant.actif,%20representant.id_representant,%20representant.nom%20AS%20nom_rep,%20representant.fichier_photo,%20representant.prenom%20AS%20prenom_rep,%20groupe_politique.nom%20AS%20nom_groupe,%20section.titre%20AS%20titre_section,%20groupe_politique.code_couleur%20FROM%20%20representant,%20groupe_politique,%20section%20WHERE%20actif=1%20AND%20representant.nom!=%27VACANT%27%20AND%20groupe_politique_id=id_groupe_politique%20AND%20section_id=id_section%20AND%20sexe=%27F%27%20ORDER%20BY%20nom_rep
* http://www.assemblee.pf/_contenu/_pages_jumi/__recherche-rep-en.php?req=SELECT%20representant.actif,%20representant.id_representant,%20representant.nom%20AS%20nom_rep,%20representant.fichier_photo,%20representant.prenom%20AS%20prenom_rep,%20groupe_politique.nom%20AS%20nom_groupe,%20section.titre%20AS%20titre_section,%20groupe_politique.code_couleur%20FROM%20%20representant,%20groupe_politique,%20section%20WHERE%20actif=1%20AND%20representant.nom!=%27VACANT%27%20AND%20groupe_politique_id=id_groupe_politique%20AND%20section_id=id_section%20AND%20sexe=%27M%27%20ORDER%20BY%20nom_rep
