### ISSUE TITLE
Colombia

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#485]
Official website of the House of Representatives: http://www.camara.gov.co/portal2011/inicio/english
(the link in the national legislature spreadsheet is broken but this one works)

Link to the representatives page: 
http://www.camara.gov.co/portal2011/representantes/honorables-representantes?view=representantes

Info on: party, constituency, term period, address, telephone, email, bills authored 

Images of representatives with bio are on this PMO website:
http://www.congresovisible.org/partidos/
http://www.congresovisible.org/congresistas/

**Comment by tmtmtmtm** [comment]
Wikipedia: https://es.wikipedia.org/wiki/Anexo:Congresistas_colombianos_2014-2018
