### ISSUE TITLE
Saint Vincent and the Grenadines

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#487]
Official website of the national assembly: http://www.assembly.gov.vc/

Link for members (21): http://www.assembly.gov.vc/index.php?option=com_content&view=article&id=28&Itemid=41

Headshots of members: http://www.assembly.gov.vc/index.php?option=com_content&view=article&id=34:head-shots&catid=4:photo-gallery&Itemid=49

There is only information about name and constituency in the above links but party association is disclosed here:  http://www.assembly.gov.vc/index.php?option=com_content&view=article&id=21&Itemid=33

**Comment by tmtmtmtm** [comment]
Duplicate of #178

**Comment by rubeenam** [comment]
Yes just realised and closed.

**Comment by tmtmtmtm** [comment]
Linking them is useful, as you have more information here than in the other ticket.

**Comment by rubeenam** [comment]
Thank you, I added more information in #178.

**Comment by tmtmtmtm** [comment]
Thanks, though I simply meant that I added the earlier comment so that this ticket would become linked from there, and I'd be able to find this information later :)
