### ISSUE TITLE
Cyprus

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#491]
http://www.parliament.cy/easyconsole.cfm/id/181

* Includes former members of the current term on a separate page
* Need to check how freeform Party/Constituency info is, or whether it's trivially separated (they're in a single field)
* Photos, contact details, email, DOB, etc.

**Comment by tmtmtmtm** [comment]
Contact details also grouped on http://www.parliament.cy/easyconsole.cfm/id/185/lang/en/

**Comment by tmtmtmtm** [comment]
Wikipedia list: https://en.wikipedia.org/wiki/List_of_members_of_the_House_of_Representatives_(Cyprus)

**Comment by wfdd** [comment]
The data for the current parliamentary period can also be found at [openpatata-data](https://github.com/openpatata/openpatata-data/tree/master/mps) in a machine-digestable format.

**Comment by tmtmtmtm** [comment]
Oh, excellent. Thanks @wfdd

**Comment by wfdd** [comment]
Thanks. I've made a mental note to update the scraper if I ever change the schema.

**Comment by tmtmtmtm** [comment]
@wfdd that would be great, thanks! Are you planning to add more information about the historic members too?

**Comment by wfdd** [comment]
Well, if I can find the information! I'm probably gonna have to visit the House Library.

**Comment by wfdd** [comment]
See http://www.parliament.cy/easyconsole.cfm/id/891/lang/en/ and http://www.parliament.cy/easyconsole.cfm/id/891/lang/en/.

**Comment by tmtmtmtm** [comment]
Oooh, useful. That doesn't look like it's going to be easy to extract data from, as large chunks of it look like they're just images. But the per-term lists (pp 294ff) are text, and there are only about 300 members, so worst case scenario, if a handful of people transcribed at least the key information by hand for a couple of people every day, it'd all be done in a few months…

**Comment by wfdd** [comment]
Looking forward to that ;)  Well, actually, the text of the lists was OCR'ed; nearly every single line contains errors.  For a taste:

```
ΑΥΥιλίδrn; ΝΙκος               Angelidis Nikos                           Angelides Nicos
Αλιάι Αχμέτ Αζίζ               Altay Ahmet ΑΖίΖ                          Altay Ahmet ΑΖίΖ
Avaσraσιόδπς Αντώνης           Ana.stasiadis AndonIs                     AnastasIades Απιοπίs
Γιάγκοu Ανδρέας                Yangu Andreas
                                                                         Yiangou Andreas
```

I could ask the publications service for the original data, but the chances I'd even get a response lie somewhere between zero and negative zero.

**Comment by wfdd** [comment]
I've also found [these](http://www2.parliament.cy/parliamentgr/002_10.htm) pages with all of the election results till 2006 on the old parliament website, though they're only in Greek.
