### ISSUE TITLE
Guyana

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#492]
Official Website: http://parliament.gov.gy
Members of Parliament: http://parliament.gov.gy/about-parliament/parliamentarian

Image, party, constituency, contact, birth date, committee memberships (full profile for most MPs)

This is the 11th Parliament. Officially first summoned to meet on June 10, 2015

**Comment by tmtmtmtm** [comment]
This only lists 34 people, but from what I can see there are meant to be 65 members?

**Comment by rubeenam** [comment]
The 35 members are elected and the rest are from a closed proportional list
which I cannot find but I am looking.

**Comment by tmtmtmtm** [comment]
The website has now added all (or most?) of the other members.
