### ISSUE TITLE
British Virgin Islands

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#512]
Website of the London office of BVI has list of parliament members: http://www.bvi.org.uk/government/houseofassembly

This website has name, image, party, constituency and bio of Assembly members (no contact info)

The parliament was called Legislative Council till 2007. the 2003-2007 parliament was the 15th legislative council. After that they were called House of Assembly. The current House of Assembly is the third. 

The official government website for House of Assembly does not have a list of members: http://www.bvi.gov.vg/house-assembly

**Comment by tmtmtmtm** [comment]
At least three of the links from that page don't exist. 

https://en.wikipedia.org/wiki/British_Virgin_Islands_general_election,_2011 seems fairly comprehensive (and there are equivalent pages for prior elections too)
