### ISSUE TITLE
Montserrat

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#514]
Official website of parliament: http://www.parliament.ms/members/
This does not disclose party affiliations which can be found here: 

http://caribbeanelections.com/knowledge/parliament/ms_parliament/ms_house.asp
Name, party info. 
Montserrat is a single nine member constituency.

**Comment by tmtmtmtm** [comment]
2009 results at http://caribbeanelections.com/ms/election2014/elections/ms_results_2009.asp

**Comment by tmtmtmtm** [comment]
http://www.elections.ms/ also has photos
