### ISSUE TITLE
Macau

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#524]
Official website: http://www.al.gov.mo/en/en.htm

No information on members here.

Name, party and constiuency information can be found in Wikipedia
https://en.m.wikipedia.org/wiki/Macanese_legislative_election,_2013#Candidates_lists_and_results

**Comment by tmtmtmtm** [comment]
All members, with links to the pages on the official site (which gives both Chinese and Portuguese versions of their names):  https://zh.wikipedia.org/wiki/澳門特別行政區立法會
