### ISSUE TITLE
Belarus

### ISSUE THREAD

**Issue by duncanparkes** [everypolitician/everypolitician-data#53]
Scrape the Belarus data.

**Comment by duncanparkes** [comment]
Data for one house is here. No parties yet I'm afraid!

https://morph.io/duncanparkes/belarus

**Comment by tmtmtmtm** [comment]
The converter does require a `party` column, even if every entry is just an empty string. 

I fixed that up as a temporary workaround (though it would be good if you added them anyway), but even then the resulting output was rather, erm, suboptimal, as you have set every name, and every constituency name, to also be empty strings...

**Comment by duncanparkes** [comment]
Ah - I  know what's happened there. I started off with 'name' and 'constituency' and changed them to 'name_en' and 'constituency_en', and because the columns already existed in morph, those other fields are still there but blank. Am I right in thinking that you cope fine with 'name_en' and 'constituency_en'? If so I'll just delete the data and rescrape.

**Comment by tmtmtmtm** [comment]
No, we added `name_en` as a quick workaround, but how to best solve the general multi-language issue is still an open question. You could always extend the Rakefile to pre-process the data as it's coming in, but I suspect it would be much simpler for you to just change the scraper to follow the currently documented requirements instead.

Also, if the number in the middle of the `details_url` (e.g. http://house.gov.by/index.php/,7508,35932,,,1,,,0.html → 35932) is suitable for use as an identifier (as it seems to be), it would be very useful if you could add that as an `id` column too.

**Comment by duncanparkes** [comment]
That number looks unique at least for the people we have at the moment, so I've added it as an 'id' column. I've also rename 'name_en' to 'name' and 'constituency_en' to 'constituency' and added a 'party' column containing all blank strings (for now).

**Comment by duncanparkes** [comment]
Todo:

  [ ] Get names in Russian and Byelorussian
  [ ] Get parties from somewhere
  [ ] Scrape Council of the Republic (http://www.sovrep.gov.by/ru/)

**Comment by tmtmtmtm** [comment]
Now live at http://data.everypolitician.org/belarus/term_table.html

**Comment by tmtmtmtm** [comment]
The list of Members at http://house.gov.by/index.php/,5489,,,,0,,,0.html doesn't seem to be easily matchable by the same 'id': might need to cross-match by their image (which seems to have the same `src` from both sets of pages)

**Comment by tmtmtmtm** [comment]
I got the Communist Party members from http://www.comparty.by/deputati

We still need to find the single AP + RPTS members.

**Comment by tmtmtmtm** [comment]
This is essentially done. We may want to add new tickets later to scrape in multiple languages, etc.
