### ISSUE TITLE
Serbia

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#539]
* Official: http://www.parlament.gov.rs/national-assembly/composition/members-of-parliament/current-legislature.487.html (incl. changes)
* Parldata: http://api.parldata.eu/rs/
* Wikipedia: https://en.wikipedia.org/wiki/List_of_current_members_of_the_National_Assembly_of_Serbia

**Comment by tmtmtmtm** [comment]
* https://en.wikipedia.org/wiki/List_of_current_members_of_the_National_Assembly_of_Serbia
* Previous at https://en.wikipedia.org/wiki/List_of_members_of_the_National_Assembly_of_Serbia,_2012–2014 etc

**Comment by tmtmtmtm** [comment]
Historic data also at http://www.parlament.gov.rs/national-assembly/composition/members-of-parliament/legislature-archive/31-may-2012-legislature.2192.html

**Comment by struan** [comment]
Looking at this

**Comment by struan** [comment]
scraper at https://morph.io/struan/serbia_national_assembly_members with current members.

Still do do are past members and also replaced members of current assembly.

**Comment by tmtmtmtm** [comment]
Thanks @struan.

This one also has a problem with incomplete recognition of prefixes: e.g. there's quite a few people left with Prof. in their name, rather than their honorific.
