### ISSUE TITLE
Oman

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#545]
The official website does not have information on Shura members anymore. The new election will be held on September. 

Names and constituencies of 84 Shura members here: http://www.omaninfo.com/news/and-winners-are2268364166.asp

There are 61 provinces from where Shura members are elected which are called Wilayats.

In the list, the word before semi colon is Wilayat. Therefore, Muscat, Baushar and Amerat are Wilayats and so on.

This is seventh period Shura, 2011-2015

**Comment by tmtmtmtm** [comment]
http://www.khaleejtimes.com/article/20111017/ARTICLE/310179889/1016 gives region info too, and looks a little easier to parse.
