### ISSUE TITLE
Zimbabwe

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#547]
Bring up to date from http://www.kuvakazim.com/position/member-of-parliament/

**Comment by JenMysoc** [comment]
We're also hoping to update this data as it's apparently out of date on the site too. It's on PDF but pages 75 - 77 of this might be useful though I'm not sure if they're scrapeable: http://www.researchandadvocacyunit.org/system/files/Coup%20de%20Grace.pdf

**Comment by tmtmtmtm** [comment]
The text can just be copied out of the document, and someone could fairly easily transform that into a spreadsheet or something, though only having a single name for many of the representatives isn't particularly ideal.

Bulawayo Province: T. Dube, Kanjoma, Malinga, Malaba, Moyo, Sikhosana, Tshuma, Sibanda,
Chiponda, Mphoko, Noedza, Ncube, Edube, Mangove.
Harare: Marara, Ganya, Gijima, Bonde, Timire, Mbeva, Hungwe, Mutero, Chakanyuka,
Hamandishe, Taruona, Bhunu, Mhlanga, Nyaruata, Grace Mugabe, Chizema, Mavenga,
Hurumbudo, Chidawu, Thambeni, Masava, Tome, Madziva, Mbizo, Mahara
Manicaland: Chituma,Mutsvangwa,Chaunga, Malianga, Chikumi, Sacco, Mlambo, Chitima,
Chinotimba, Mutomba, Gondo, Nzuma, Machiwana, Muchinguri, Mawire, Maradzamunda,
Chinamasa, Majachani, Made, Manditeve, Kadzima, Nyhanhongo, Chitepo, Samvu, Dumbura,
Mukumi, Gwarandimba, Madiro, Mushowe.
Mashonaland East: Kapfunde, Kachebu, Gotora, Manguwo, Mangude, Kachepa, Kanjeve,
Navaya, Musa, Kachoto, Karima, Mushure, Bhima, Kanyebwe, Kaguma, Matinhira,
Murirwagoto, Zhanda, Mujahwe, Zhangazha, Matsangura, Mubaiwa, Sekeremayi, Muranga,
Parirenyatwa, Zemura, Nyakudanga, Kadiki, Chinake, Jakopo, Taguma.
Mashonaland Central: Karigoka, Titipanyanga, Mbambi, Mazikanyi, Chisasa, Chamutswakina,
Mombeshora, Paradza, Musona, Magaradzikwa, Chiropa, Makazika, Mavangira, Chitewe,
Gushu, Chiwara, Gatsi, Chidengwende, Zinyemba, Kambidzi, Mahungira, Machena, Mucheli,
Saviour Kasukuwere;
Mashonaland West: Siyajamba, Mombeshora, Makume, Chiyangwa, Madzongwe, Mufumira,
Chaderopa, Ngomalala, Muvi, Gava, Madara, Rodvi, Chanetsa, Gumbo, Chombo, Zhuwao,
Chidongoma, Muchenge, Chidhakwa, Bietebit, Mutsnanga, Madvidi, Zinyambi, Wenjere,
Chengeta, Haritotis.
Masvingo: Meve, Shumba, Magwema, Muzara, Moyo, Shumba, Chimeka, Mawere, Gavaza,
Malulueke, Shumba, Huni, Manyindangadna, Matipa, Matorofa, Babhuni, Hungwe, Mangwana,
Makaza, Maluleke, Mahiya, Chivinga, Sithole, Matuke, Chikwama, Mandebvu.
Matabeleland South: E. Ndiweni, Enyathi, Mohadi, Maboyi, Mudawu, Ncube, Ndlovu, Hove,
Mathuthu, Nkomo, S.K. Moyo, Ncube, Ndlovu, Moyo, Ncibi, Mpofu, Ndlovu.
Matabeleland North: Nyoni, Dube, Mpofu, Fanuel, Nkomo, O. Mpofu, Mbambo, Jonathan
Moyo, Sibanda, Moyo, Mathema, Tshuma, Mguni, Moyo, Ndebele, Ndlovu, Ndebele,
Muzamba, Mudenda, Mpofu.
Midlands: Ncube, Tapfuma, Mavima, Chikomba, Singi, Chakanyuka, Pfundira, Muri, Auxillia
Mnangangwa, Muzenda, Chimbi, Sithole, Majube, Emerson Mnangagwa, Spiki, Zvidzai,
Matemandanda, Maboshere, Masuka, Chidziva, Mathulisa, Magura, Gumbo, Mataga, July
Moyo, Shiri, Mataka.
Youth League: Marovahoko, Ncube, Masuku, Takarusikirwa, Dombondzungu, Ngwenya,
Zinyoro, Taruwona, Dhliwayo, Chipanga, Mathuthu, Tongai Kasukuwere, Hamandishe,
Malinga, Matonhodza, Nyanguwara, Mpofu, Kazizi, Simbanegari, Ndlovu.
Womens League: Mutumbwa, Ncube, Mhlanga, Chipato, Chitura, Chatibura, Sandi, Nhari,
Mahoka, Chinamona, Malinga, Mahomva, Mathuthu, Mutsvangwa, Mohadi, Musarurwa,
Sibanda, Vareta, Sibanda.
Mugabe’s selection: Simbarashe Mumbengengwi, Josephine Gandiya, Walter Mzembi, Charles
Tavengwa, Sikhanyiso Ndlovu, Absolomo Sikhosana, Mudomeni Chivende, Aguy Georgias,
Pupurai Togarepi, Supa.Mandiwanzira.

ANNEXURE D
Party Suspensions and expulsions

Expelled

Joice Mujuru, Didymus Mutasa, Rugare Gumbo, Jabulani Sibanda, Dzikamai Mavhaire,
Kudakwashe Bhasikiti, Temba Mliswa Ray Kaukonde, Olivia Muchena, Claudius Makova,
David Butau, Kudakwashe Gope.

Suspended

Bulawayo: Callistus Ndlovu, Christopher Dube, Elifasi Mashabe, Charles Chiponda, Nicholas
Mhlanga, Canaan Ncube, Bertha Moyo, Methusela Ndlovu, Quiet Moyo, Bheki Dube, Calvin
Musuta and Noma Mokoena.
Harare: Albertina Bwititi, Varaidzo Mupunga, Eva Chaneta, Clyde Mutero, Susan Chuma,
Torongo Torongo, Tongai Nheta, Angeline Matambanadzo, Prince Shinya, Brian Hwenjere,
Andrew Tiriboyi, Munyaradzi Mugomeza, Olivia Mususa and Tendai Diwa, Tendai Savanhu,
Christopher Chigumba, Munyaradzi Banda, Noah Mangondo and Amos Midzi.
Manicaland:392 Munacho Mutezo.
Mashonaland Central: Luke Mushore, Joseph Mapiki, Dorothy Mashonganyika, Alice Muropa,
Rashiwe Gambiza, Mawodzeka Mujubeki, Stanford Mugari, Nicholas Goche, Dougmore
Chimukoko and Titus Manyika.
Mashonaland East: Felix Mhona, Simba Mudarikwa, Tendai Makunde, Washington Musvaire,
Phineas Chihota, George Katsande, Lucky Kandemiri, Vernon Muringayi, John Mushayi, Peter
Murwira, Marble Kaundikidza, Taurayi Pasirayi, Getrude Mariwo, Boniface Mutize, Stephen
Chiurai, Sithembile Makamba, Petronella Musarurwa, Charity Chakanyuka, Musekiwa
Masendeke, Prosperity Danga, Nhamo Chikango and Angeline Mafuta.
Mashonaland West: Webster Shamu, Sylvester Nguni Kindness Paradza, Joshua Chakona,
Adrian Musiiwa, Stephen Karenga, Constance Shamu, Jackson Chizanga, Dominic Muza,
Mernard Waneke and Talent Muduvuri.
Masvingo: Paul Chimedza, Denford Masiya, Oliver Huruva, Shylett Moyo, Joshua Matakanure,
Mike Musorowegomo, Wilson Makonya, Kenneth Sibanda, Tongai Muzenda, John Mutomana,
Gift Jayaguru, Darlington Chiwa, John Mutomana, C. Bhasikiti, M. Mujakachi, M. Demba, S.
Majatame, J. Chikupe, F.K. Dera, E. Chapungu, E. Chiduwa, L. Shindi, E. Mangove, Tendai
Magomana, Simbarashe Ndakaripei, Mbizvo Rushambwe, Otwell Chikosi, Killian Gwanetsa,
Tranos Huruba and Last Chisi.
Matabeleland North: None or unknown.
Matabeleland South: Andrew Langa, Jabulani Phetshu Sibanda, Jeremiah Langa, Moffat
Sithole, Ollen Ncube, Morris Muhambi, Lungisani Nleya, Malaki Nkomo, Alice Dube, Clara
Langa, Greater Ncube, Vongai Mpofu, Alma Mkwebu, Ndabayabo Ndlovu, Tafirenyika
Seremani and Moses Langa.
Midlands: Francis Nhema, Flora Bhuka, Tafanana Zhou, Fred Moyo, Tariro Mutingwende,
Dorothy Mhangami, Cliff Manungo, Renias Madende, Stephen Ngwenya, Francis Chikwira,
Edmond Mkaratigwa, Fadzai Ntabeni, Danisa Mujere, Clara Ngwenya, Aida A. Tongogara,
Sheilla Midzi, Theopold Takanai, Jaison Machaya and Simbarashe Zhoake, Chiratidzo Mabuwa

**Comment by tmtmtmtm** [comment]
Done
