### ISSUE TITLE
Algeria

### ISSUE THREAD

**Issue by briatte** [everypolitician/everypolitician-data#567]
Lower house, full listing of current legislature:

http://www.apn.dz/fr/les-membres?searchcondition=2&cat_id=83&cf31=&cf36=&cf38=&cf40=&Itemid=715&option=com_mtree&task=listall&sort=link_name

Upper house (Arabic only; still stuck in the 1990s re: HTML structure):

http://www.majliselouma.dz/

**Comment by briatte** [comment]
[Here's a scraper in R](https://gist.github.com/briatte/175bf29f73e3c79b3041). Results included.

**Comment by briatte** [comment]
Okay, first try at Ruby below. Largely plagiarised from [your scraper for Morocco](https://github.com/tmtmtmtm/morocco-house-of-representatives/blob/master/scraper.rb).

```rb
#!/bin/env ruby
# encoding: utf-8

require 'scraperwiki'
require 'nokogiri'
# require 'open-uri'
require 'colorize'

require 'pry'
# require 'open-uri/cached'
# OpenURI::Cache.cache_path = '.cache'

class String
  def tidy
    self.gsub(/[[:space:]]+/, ' ').strip
    self.gsub(/\t/, '')
  end
end

def noko_for(url)
  Nokogiri::HTML(open(url).read)
  # Nokogiri::HTML(open(url).read, nil, 'utf-8')
end

def scrape_page(url)
  noko = noko_for(url)
  puts url.to_s.yellow

  noko.css('div.listing-summary').each do |div|
    data = {
      id: div.css('h3 a/@href').text, # do -not- use .split("/").last here
      name: div.css('h3').text.tidy,
      type: div.css('.category a').text,
      party: div.css('#field_31 span:nth-child(2)').text,
      constituency: div.css('.fields .row0:nth-child(2) span:nth-child(2)').text.tidy,
      image: div.css('img/@src').text,
      term: 7,
    }
    print data
    # ScraperWiki.save_sqlite([:id, :term], data)
  end
  return noko
end

noko = scrape_page('http://www.apn.dz/fr/les-membres?searchcondition=2&cat_id=83&cf31=&cf36=&cf38=&cf40=&Itemid=715&option=com_mtree&task=listall&sort=link_name')

last = noko.css('.pagination-list a/@href').last.text
last = last.gsub(/(.*)page(\d+)(.*)/, '\\2').to_i

for i in (2..last).to_a
  p = "http://www.apn.dz/fr/les-membres/all/page" + i.to_s + "?searchcondition=2&sort=link_name"
  scrape_page(p)
end
```

**Comment by tmtmtmtm** [comment]
Excellent, thanks! Will look in detail tomorrow

**Comment by tmtmtmtm** [comment]
This is great!

A couple of questions/notes:

* What was your concern with reducing the id to the final element? The structure varies, but the final element seems unique to me (and is exposed directly as the data-link-id on the relevant `div`)
* I tweaked the constituency information to generate area IDs in the same format as [http://docs.opencivicdata.org/en/latest/proposals/0002.html](OCD division IDs] — we've switched to using these where possible now, though we still haven't gone back and 'fixed' all the historic ones.
* There's a 'by gender' filter, so I switched to running two searches, to grab that info too (and just iteratively following the 'Next' link, where there is one, rather than pre-counting pages, to avoid having to build the URL each time)

Scraper is now live at https://morph.io/tmtmtmtm/algeria-assemblee

**Comment by tmtmtmtm** [comment]
New ticket for historic data at #569

**Comment by tmtmtmtm** [comment]
Hmmm. This seems to include too many members! There are only meant to be 462 seats, but we have 478. I'm guessing that some of the `type`s should be omitted, but it's not obvious to me which. We currently have:

* National: 452
* Députés nommés au gouvernement: 9
* International: 8
* Députés décédés: 4
* Députés démissionnaires: 3
* Députés appelés à d'autres fonctions: 2

**Comment by briatte** [comment]
Hi,

> What was your concern with reducing the id to the final element? The structure varies, but the final element seems unique to me (and is exposed directly as the data-link-id on the relevant div)

I was referring to the different URL structure before the actual `id`, which does seem unique.

> I tweaked the constituency information to generate area IDs in the same format as [http://docs.opencivicdata.org/en/latest/proposals/0002.html](OCD division IDs] — we've switched to using these where possible now, though we still haven't gone back and 'fixed' all the historic ones.

Great stuff! This is a better idea than using Wikipedia handles like I did so far. Am I right that [only a few countries](https://github.com/opencivicdata/ocd-division-ids/tree/master/identifiers) have been mapped so far?

> There's a 'by gender' filter, so I switched to running two searches, to grab that info too (and just iteratively following the 'Next' link, where there is one, rather than pre-counting pages, to avoid having to build the URL each time)

Nice trick :)

I'll update the R code to match yours.

**Comment by briatte** [comment]
> Hmmm. This seems to include too many members!

Don't think so: MPs in office are those marked "National" (452) or "International" (8), which sums to 460. My guess is that the two MPs who received another mandate ("Députés appelés à d'autres fonctions") have not been replaced: perhaps they can return to their MP mandate after they are done with whatever they are doing.

The three other categories are MPs who were nominated to the executive ("nommés au gouvernement", which supposes resigning from the legislative), who died ("décédés"), or who just resigned ("démissionnaires"). I'm pretty sure those MPs were replaced, as the Constitution should require.

**Comment by tmtmtmtm** [comment]
> Am I right that only a few countries have been mapped so far?

I think so. We've created a few more, but I'm waiting until we've done a few more to see if issues arise, or we discover we've done something fundamentally wrong, before submitting them. 

> The three other categories are MPs who were nominated to the executive ("nommés au gouvernement", which supposes resigning from the legislative), who died ("décédés"), or who just resigned ("démissionnaires"). 

Thanks for the explanations. The biggest issue here is that we currently have no way of saying that someone is no longer a member without having an actual date when that happened. This means that things like the count of seats per party isn't accurate. Don't suppose you know somewhere where we might find those dates, other than simply looking for press articles or the like for each in turn?

**Comment by briatte** [comment]
I don't know where to find the information, and there's a fair chance you might be right about having to look into the press, since even the MP profiles do not report anything about their status, e.g.

http://www.apn.dz/fr/les-membres/deputes-appeles-a-d-autres-fonctions/90-chorfi-miloud

How about using the start date of the term instead?

**Comment by tmtmtmtm** [comment]
Yeah — I checked the Arabic version in case that had more information, but there was nothing extra there:

  http://www.apn.dz/ar/les-membres-ar/membres-7eme-legislature-ar/deputes-appeles-autres-fonctions/393-

> How about using the start date of the term instead?

I'm slightly hesitant to include information that I explicitly know is wrong, as that seems slightly different from just having missing data — though it may well be the most practical answer. I'll give it some more thought.
