### ISSUE TITLE
US Virgin Islands

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#570]
Official website of the legislature: http://www.legvi.org/#
link to the senators page has name, images, constituencies and brief bio.

The parties from the candidates can be taken from this wikipedia page:
https://en.wikipedia.org/wiki/United_States_Virgin_Islands_gubernatorial_election,_2014

**Comment by tmtmtmtm** [comment]
You mean https://en.wikipedia.org/wiki/United_States_Virgin_Islands_general_election,_2014 ?

**Comment by rubeenam** [comment]
Oh, this looks better.
