### ISSUE TITLE
Turks and Caicos Island

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#572]
Official website: http://www.gov.tc/index.php/government/house-of-assembly

The name of the parliament has been changed from Legislative Council to House of Assembly in 2006. The number of members are 19, not 21. This information has not been updated in all wikipedia sites.

Of the 19, 10 members are directly elected, 5 are at large members. Party information for these 15 members can be taken from https://en.wikipedia.org/wiki/Turks_and_Caicos_Islands_general_election,_2012 (In the list, all names till Josephine Connolly)

Government website has name, image, constituency and bios for some.

**Comment by tmtmtmtm** [comment]
Scraper for official site: https://morph.io/tmtmtmtm/turks-and-caicos-assembly

**Comment by tmtmtmtm** [comment]
* Wikipedia scraper: https://morph.io/tmtmtmtm/turks-and-caicos-assembly-wikipedia
* Wikidata scraper: https://morph.io/tmtmtmtm/turks-and-caicos-assembly-wikidata
