### ISSUE TITLE
Norfolk Island

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#574]
Official website: http://www.norfolkisland.gov.nf/legislativeassembly/legislativeassembly.html

Names of nine Legislative members.
All 9 candidates were elected as independents.

This is the 14th Legislative Assembly that came into effect from 13 March 2013

**Comment by tmtmtmtm** [comment]
Where did the date of March 13th come from? The page linked says that it started on March 20th.

**Comment by rubeenam** [comment]
On Wikipedia it says the assembly was elected on thT date https://en.m.wikipedia.org/wiki/Norfolk_Legislative_Assembly

**Comment by tmtmtmtm** [comment]
Ah, OK. In general we prefer to use the dates of the Assembly itself, rather than the date of the election, just falling back on election dates where we can't find the more precise info.
