### ISSUE TITLE
Saint Kitts and Nevis

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#576]
Official website: http://sknis.info/about/
But it does not give information about National Assembly.

Names, constituencies and parties of NA members can be found here
http://www.caribbeanelections.com/knowledge/parliament/kn_parliament/kn_house.asp

and here: http://psephos.adam-carr.net/countries/s/stkitts/stkitts2015.txt

Bios of few leaders with images are available in the caribbeanelections site
http://www.caribbeanelections.com/knowledge/biography/country_list/kn_bio.asp

**Comment by tmtmtmtm** [comment]
Wikipedia election results https://en.wikipedia.org/wiki/Saint_Kitts_and_Nevis_general_election,_2015

**Comment by tmtmtmtm** [comment]
Wikipedia scraper: https://morph.io/tmtmtmtm/saint-kitts-and-nevis-elections-wikipedia

**Comment by tmtmtmtm** [comment]
Wikidata scraper: https://morph.io/tmtmtmtm/saint-kitts-and-nevis-elections-wikidata
