### ISSUE TITLE
South Korea

### ISSUE THREAD

**Issue by briatte** [everypolitician/everypolitician-data#577]
http://en.pokr.kr/ has incredibly good information that goes really far back in time!

**Comment by tmtmtmtm** [comment]
Yeah — this is a great group; we've had some contact with them in the past.

Their API doesn't expose most of the data, though, unless it's through undocumented endpoints (compare http://en.pokr.kr/person/19601167 with http://api.popong.com/v0.1/person/19601167?api_key=test)

Their raw current data is slightly better (https://github.com/teampopong/data-assembly/blob/master/assembly.json) though some fields look a little bit tricky to unpack.

I suspect https://github.com/teampopong/data-for-rnd may be the key here. `candidacies.csv` looks like a particularly useful dataset, even if just filtered on `is_elected = y`

**Comment by briatte** [comment]
I'm also having trouble with the API re: bills (it [does not seem to return cosponsors](https://github.com/teampopong/pokr.kr/issues/50), and there's things I [don't yet understand](https://github.com/teampopong/pokr.kr/issues/38) about how the bills work).

https://github.com/teampopong/data-for-rnd looks great indeed!

**Comment by briatte** [comment]
Aside: I managed to [plot what I wanted](http://f.briatte.org/parlviz/gukhoe/plots.html) from the data provided by Team Popong. I have never seen a country with so many political parties over time. Even Argentina has more structured factions.

**Comment by e9t** [comment]
Member of Team POPONG here!
Thanks for the great work. Please let me know if you need any assistance regarding South Korea.
