### ISSUE TITLE
Greenland: new terms

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#5773]
http://www.ina.gl/inatsisartuthome/sammensaetning-af-inatsisartut.aspx

**Comment by wfdd** [comment]
Scraper for all terms at https://morph.io/wfdd/inatsisartut-scraper.

**Comment by wfdd** [comment]
Also fixed #381 and the incorrect numbering of terms.

**Comment by wfdd** [comment]
This can be closed now.

**Comment by tmtmtmtm** [comment]
thanks @wfdd
