### ISSUE TITLE
Israel

### ISSUE THREAD

**Issue by briatte** [everypolitician/everypolitician-data#579]
I just wrote a [quick scraper](https://github.com/briatte/knesset) for Israel. It uses [Open Knesset](https://oknesset.org/) as the main data source, and gets a few more things from the official Knesset website. Since the scraper is written in R, it won't be useful, but here's a few pointers to the raw data.

Main source for recent terms:

https://oknesset.org/parties-members/20/
https://oknesset.org/parties-members/19/
https://oknesset.org/parties-members/18/

If you need more historical data:

http://www.knesset.gov.il/mk/eng/mkindexbyknesset_eng.asp?knesset=20
http://www.knesset.gov.il/mk/eng/mkindexbyknesset_eng.asp?knesset=19
http://www.knesset.gov.il/mk/eng/mkindexbyknesset_eng.asp?knesset=18
etc. (goes back to 1)

To list all women from a given term:

http://www.knesset.gov.il/mk/eng/MKIndexByKnesset_eng.asp?knesset=20&view=2
http://www.knesset.gov.il/mk/eng/MKIndexByKnesset_eng.asp?knesset=19&view=2
http://www.knesset.gov.il/mk/eng/MKIndexByKnesset_eng.asp?knesset=18&view=2
etc. (goes back to 1)

Open Knesset uses the same numeric ids as the Knesset, which is nice.

Also, there's no constituencies in Israel, so there's no work to do on that end.

This one should be easier than Italy :)

**Comment by tmtmtmtm** [comment]
Was there information in OpenKnesset that wasn't also in the official site, or was it just a case that you scraped it first, and then needed to top it up?

NB: you don't need to run the second 'by gender' search. Even though the icons look identical to me, the http://www.knesset.gov.il/mk/eng/mkindexbyknesset_eng.asp?knesset=20 etc pages, do actually wrap each person with `MKIconM` or `MKIconF`

**Comment by tmtmtmtm** [comment]
Did you find a source for the dates of faction changes? The official site simply lists the different factions that someone was in during a specific Term, but I can't spot anything that lists when the switches happened.

**Comment by briatte** [comment]
> Was there information in OpenKnesset that wasn't also in the official site, or was it just the case that you scraped it first, and then needed to top it up?

First option: laziness. I was primarily interested by the bills, and didn't bother going for the [real thing](http://knesset.gov.il/privatelaw/Plaw_display.asp?lawtp=1), which looks painful (Hebrew + JavaScript).

> NB: you don't need to run the second 'by gender' search. Even though the icons look identical to me, the http://www.knesset.gov.il/mk/eng/mkindexbyknesset_eng.asp?knesset=20 etc pages, do actually wrap each person with MKIconM or MKIconF

Thanks, I forgot to check that. The icons look identical to me too. That's perhaps too much gender equality.

**Comment by briatte** [comment]
Sorry, forgot to answer the main point:

> Was there information in OpenKnesset that wasn't also in the official site

I used the English pages of the Knesset to get MP names that I could easily process when dealing with duplicate names. There a few duplicates if you parse the MPs by parliamentary faction, because some MPs will be listed twice or thrice in every parliamentary faction to which they belong or have belonged.

[Here's the part of my scraper that handles this issue for Knessets 18–20](https://github.com/briatte/knesset/blob/master/data.r#L227-L238). The transitions are related to Ehud Barak forming his own (short-lived) party, and to a fraction of Likud turning even more to the right.

I have not checked whether the official Knesset pages suffer from the same issue, although I suspect they must do in a way, since Open Knesset tightly relates to them.

**Comment by briatte** [comment]
Continued:

> Did you find a source for the dates of faction changes?

I have used the affiliation that Open Knesset reports on the individual page of each MP as the primary affiliation, but I have not seen a detailed list of faction transitions.

This issue also affects a country like Italy, and as you must have noticed, it is almost impossible to keep track of these changes, because MPs not only switch factions (parliamentary groups), they also switch parties, usually at undisclosed (or unmonitored) dates. [The data for France](https://github.com/regardscitoyens/rattachement-financier-parlementaires), which are updated annually, are not always available elsewhere.

**Comment by tmtmtmtm** [comment]
I wanted all data back to the start, so simply worked my way through the full alphabetical list of members at http://www.knesset.gov.il/mk/eng/MKDetails_eng.asp

I think that should have avoided the issue of duplicates.

The factions are mess though — for now I've simply grabbed the last one from the list for a given Term.

**Comment by briatte** [comment]
> I think that should have avoided the issue of duplicates.

It seems to, which means that Open Knesset is using some other method to get the factions.

> The factions are [a] mess though

… and thereby truly reflect the state of Israeli politics :P
