### ISSUE TITLE
Oxfam Data - UK

### ISSUE THREAD

**Issue by paullenz** [everypolitician/everypolitician-data#584]
Data fields required (by mid September)
https://github.com/everypolitician/everypolitician-data/blob/master/data/UK/Commons/term-56.csv

- Name (we have)
- Party (we have)
- Constituency (we have)
- Email (scrape from http://www.parliament.uk/mps-lords-and-offices/mps/)
- contact number (assume that we can scrape from http://www.parliament.uk/mps-lords-and-offices/mps/)
- Facebook ( scrape from http://www.parliament.uk/mps-lords-and-offices/mps/ unless a more canonical version exists)
- Twitter- we have

**Comment by dracos** [comment]
There is an API at http://data.parliament.uk/membersdataplatform/memberquery.aspx, there is no need for scraping. The API will be more up to date for Twitter.

**Comment by tmtmtmtm** [comment]
Scraper for data.parliament.uk info at https://morph.io/tmtmtmtm/uk-parliament-members
