### ISSUE TITLE
Oxfam Data - Australia

### ISSUE THREAD

**Issue by paullenz** [everypolitician/everypolitician-data#587]
Data fields required (by mid September)

Existing data - https://github.com/everypolitician/everypolitician-data/blob/master/data/Australia/Representatives/term-44.csv

Name (we have)
Party (we have)
Constituency (we have)
Email (hand source missing email addresses from personal pages - e.g. http://www.davidgillespie.com.au )
contact number (scrape from http://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=LL6 unless a more canonical version exists)
Facebook - none currently, can scrape from http://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=LL6 unless a more canonical version exists)
Twitter  - we have

**Comment by dracos** [comment]
There are Facebook entries for c. 120 of the representatives in the data already (in the JSON, not the CSV).
