### ISSUE TITLE
Namibia

### ISSUE THREAD

**Issue by duncanparkes** [everypolitician/everypolitician-data#59]
Looks like a good candidate to do soon as there are 6 historical terms:

http://www.parliament.gov.na/index.php?option=com_contact&view=category&id=104&Itemid=1516

**Comment by tmtmtmtm** [comment]
?? I'm getting this as that page:

![namibia 2015-05-13 at 10 37 39](https://cloud.githubusercontent.com/assets/57483/7607787/2674b4ba-f95c-11e4-904e-b60aa51968c3.png)

Do you mean http://www.parliament.na/ ?

**Comment by duncanparkes** [comment]
Odd - I copied it from my browser's location bar, and that's the URL I still have open.

**Comment by tmtmtmtm** [comment]
Google also sees the same thing as me:
  http://webcache.googleusercontent.com/search?q=cache:www.parliament.gov.na/

Not sure which Morph will see, but as it looks like parliament.na is the real site, it's probably best to use that.

**Comment by duncanparkes** [comment]
Morph seems to see the same thing as me, which is lucky.

**Comment by duncanparkes** [comment]
Data for Namibia is here

https://morph.io/duncanparkes/namibia

This includes all terms of both the National Assembly and the National Council, but not currently email addresses, which are filled in by javascript to prevent robots picking them up.

**Comment by tmtmtmtm** [comment]
You said you were going to drop the term information into a separate table for this one? Doing it similarly to https://morph.io/tmtmtmtm/portugal-democratica-scraper would be good...

**Comment by duncanparkes** [comment]
So the important bits are:

`
term_data = {
id: termname[/^(\d+)/,1],
name: termname,
start_date: start_date,
end_date: end_date,
}
ScraperWiki.save_sqlite([:id], term_data, 'terms')
`

Which fields are compulsory? Do you need start and end dates? I'm not sure I have them!

**Comment by tmtmtmtm** [comment]
those are the four things we use. Ordering happens by dates, so we do need them. They can't be *that* hard to find, surely?

**Comment by duncanparkes** [comment]
I'm sure I can come up with something - do they have to be date dates, or are just years good enough?

**Comment by tmtmtmtm** [comment]
Full dates are better, but years are sufficient.

**Comment by duncanparkes** [comment]
Great.

**Comment by tmtmtmtm** [comment]
Grabbing the email addresses doesn't look particularly difficult... They're all in `jsn-table-column-email` blocks in the form: 
```
 var addy61752 = 'm.n&#97;k&#117;tw&#105;m&#97;' + '&#64;';
 addy61752 = addy61752 + 'p&#97;rl&#105;&#97;m&#101;nt' + '&#46;' + 'n&#97;';
```

and converting from "97" to "a" etc is presumably pretty trivial in python?

**Comment by tmtmtmtm** [comment]
(Or maybe this one would be better as a phantomJS scarper?)

**Comment by duncanparkes** [comment]
Indeed - they're doable. I've just not done them yet.

**Comment by duncanparkes** [comment]
PyExecJS might help - or I should just manually write something to parse that. I guess it depends on how hard they work to make them difficult to read (whether they always do the same sort of thing, or mess around a bit randomly)

**Comment by duncanparkes** [comment]
'4th National Council: 2010 - 2015' is the kind of data we have for each term. I'm assuming what you'd like here is

**Comment by duncanparkes** [comment]
I assume general - I'll just repeat the name for now.

**Comment by tmtmtmtm** [comment]
It depends on whether they're the same or not. A majority of countries seem to keep the terms in sync, though there are a reasonable number who stagger them. We only really cope cleanly with the first case right now, though we'll need to solve the latter at some point in the not-too-distant future.

**Comment by duncanparkes** [comment]
I'm going to hop back into this one and get the email addresses while I'm thinking PyExecJS.

**Comment by tmtmtmtm** [comment]
What's the status of this? Is it ready now?

**Comment by duncanparkes** [comment]
I believe this is all ready. The scraper is running at the moment, and going by last night, may take about 40 minutes.

**Comment by tmtmtmtm** [comment]
Great, thanks.
