### ISSUE TITLE
Burundi Assembly 2015

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#610]
https://en.wikipedia.org/wiki/Burundian_legislative_election,_2015

The official website still lists the 2010 members, and I haven't yet been able to find anything other than the party allocations.

**Comment by duncanfwalker** [comment]
Looks like it might be online now (http://www.assemblee.bi/Liste-des-deputes). Is the process now just to write a scraper and host it somewhere (ie morph.io)?

**Comment by tmtmtmtm** [comment]
Ah, excellent — and the print based version is even easier to scrape:
  http://www.assemblee.bi/spip.php?page=imprimer&id_article=418

Yes — a morph.io based scraper is ideal. Are you going to have a go at this one? The columns should map cleanly as id{1}, name{2}, national_identity, gender{3}, party, area 


{1} though if you could prefix each with '2015-' that would avoid clashes with any previous terms
{2} removing the 'Hon.' prefix would be useful
{3} converted to 'male' or 'female'

**Comment by duncanfwalker** [comment]
Yes, thanks for the tips, I'll have a go at the weekend

**Comment by tmtmtmtm** [comment]
Great! Yell if you're unsure about anything.

**Comment by duncanfwalker** [comment]
Just doing the scraper now https://morph.io/duncanfwalker/burundi-national-assembly

Should I be creating a terms.csv as well?

**Comment by tmtmtmtm** [comment]
That's excellent, thanks! We already have a terms file from the scraper for the earlier term, so I'll just add details of this term by hand when merging these. Do you happen to know the exact start_date for the term?

**Comment by duncanfwalker** [comment]
No, just looking on http://www.assemblee.bi/ now

**Comment by tmtmtmtm** [comment]
From http://www.reuters.com/article/2015/07/27/us-burundi-politics-idUSKCN0Q11V820150727, looks like it was July 27th

**Comment by duncanfwalker** [comment]
Well spotted

**Comment by tmtmtmtm** [comment]
@duncanfwalker This is currently staged at https://everypolitician-viewer-pr-564.herokuapp.com/burundi/assembly/term-table/2015.html — give the go-ahead, and I'll merge it; or if you want to make any other tweaks, let me know and I'll rebuild.

**Comment by duncanfwalker** [comment]
Looks great

**Comment by tmtmtmtm** [comment]
Now live: http://everypolitician.org/burundi/assembly/term-table/2015.html

Thanks for you help!
