### ISSUE TITLE
Afghanistan

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#629]
http://wolesi.website/pve/document.aspx?Cat=37

* https://en.wikipedia.org/wiki/House_of_the_People_(Afghanistan)
* https://www.wikidata.org/wiki/Q2108181
* Seats: 249

**Comment by tmtmtmtm** [comment]
This is nasty to scrape as each individual Member's page has a different layout to the others!

**Comment by tmtmtmtm** [comment]
* https://en.wikipedia.org/wiki/House_of_the_People_(Afghanistan)
* https://www.wikidata.org/wiki/Q2108181
* Seats: 249
* Last election: 2010 (term [finished 22 June 2015](https://en.wikipedia.org/wiki/Afghan_parliamentary_election,_2015)]

**Comment by Abbie2020** [comment]
There appears to be a new website with more consistent formatting but a mixture of Arabic and English profiles making it tricky.

http://afgparliament.org/wj/index.php/en/contact_senator

**Comment by tmtmtmtm** [comment]
Oh, excellent. Great find!
