### ISSUE TITLE
American Samoa

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#630]

**Comment by lizconlan** [comment]
looking for data sources for this today

**Comment by lizconlan** [comment]
American Samoa has a bicameral legislature (the **Fono**) comprising **Senate** (upper) and **House of Representatives** (lower) chambers. It also has an elected head of government post - the Governor and their deputy (the Lieutenant Governor), elected together on a single ticket.

## House 
House elections are held every 2 years to select 21 representatives; 20 elected by ballot across 17 voting districts and 1 by "public meeting". The most recent was in 2014, most of the results here (under "Fono"): https://en.wikipedia.org/wiki/American_Samoan_general_election,_2014

(It is common - including on the official vote results paperwork - to differentiate between districts of the same name by appending "# 1", "# 2" etc in the order they appear in the district list, I'm tempted to edit the Wikipedia results page accordingly)

As this listing only covers conventional voting, it omits the representative for Swains Island who is cited by various news sources as being **Su’a Alexander Eli Jennings** (http://pidp.org/pireport/2014/November/11-04-16.htm)

## Senate
Senate elections are held every 4 years to select 18 representatives. The most recent was in 2012, with Wikipedia claiming this to be the most recent list of representatives: https://en.wikipedia.org/wiki/American_Samoa_Senate

## Gubernatorial
Held every 4 years, the most recent was in 2012. https://en.wikipedia.org/wiki/American_Samoa_gubernatorial_election,_2012

--
Historic data for the legislative elections is patchy at best, although the elections for the governor seem to have better coverage.

**Comment by tmtmtmtm** [comment]
Thanks @lizconlan

**Comment by lizconlan** [comment]
accidentally skipped footnote - on the whole, especially within the House of Representatives, candidates are 'non-partisan' rather than aligning with a political party (see https://en.wikipedia.org/wiki/Politics_of_American_Samoa)

**Comment by lizconlan** [comment]
The data at https://en.wikipedia.org/w/index.php?title=American_Samoa_House_of_Representatives&oldid=395051257 appears to be for the 2008 House of Representatives election (after briefly cross-checking with the archived "unofficial" results from the old Elections Office site https://web.archive.org/web/20081126201402/http://205.161.14.36/results_rep_2008.htm)
