### ISSUE TITLE
Italy (Senate): split email addresses

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#6330]
Currently has values like 'donatella.albano@senato.itmailto:donatella.albano@gmail.commailto:donatella.albano@gmail.com'

**Comment by tmtmtmtm** [comment]
Also has multiple facebook entries along the lines of 'https://www.facebook.com/laura.cantini.98/www.facebook.com/Laura.Cantini.98'

**Comment by chrismytton** [comment]
There is also at least on instance on [this page](http://politici.openpolis.it/politico/franco-vazio/316193) where there's a `mailto:` link which is actually a link to a youtube video!

![screen shot 2016-04-21 at 10 04 20](https://cloud.githubusercontent.com/assets/22996/14701998/743b8c7c-07a8-11e6-9197-214acee6b4a5.png)

This is getting picked up by [the part of the scraper that scans for email addresses](https://github.com/tmtmtmtm/openpolis-scraper/blob/1e496b4d9d6fc82e493307e938b1ff7c132c9a69/scraper.rb#L33).

**Comment by tmtmtmtm** [comment]
Fixed in https://github.com/tmtmtmtm/openpolis-scraper/commit/1e496b4d9d6fc82e493307e938b1ff7c132c9a69 and https://github.com/tmtmtmtm/openpolis-scraper/commit/69bdd05d9385e98614d20c646b45ed11448739f9
