### ISSUE TITLE
Cambodia

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#637]
http://national-assembly.org.kh

**Comment by FOIMonkey** [comment]
https://en.wikipedia.org/wiki/List_of_MPs_of_the_National_Assembly_of_Cambodia
http://www.national-assembly.org.kh/group-article/57

**Comment by tmtmtmtm** [comment]
Wooo. Thanks @FOIMonkey 

And historic at
1. http://www.national-assembly.org.kh/group-article/48 
2. http://www.national-assembly.org.kh/group-article/49 
3. http://www.national-assembly.org.kh/group-article/49 
4. http://www.national-assembly.org.kh/group-article/50
