### ISSUE TITLE
Guinea-Bissau

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#650]
http://anpguinebissau.org/

**Comment by tmtmtmtm** [comment]
* current: http://anpguinebissau.org/processo-legislativo/copy_of_parlamentares/em-servico (but empty!)
* 8th: http://anpguinebissau.org/processo-legislativo/copy_of_parlamentares/ex-parlamentares/viii-legislatura/view
* 7th: http://anpguinebissau.org/processo-legislativo/copy_of_parlamentares/ex-parlamentares/vii-legislatura/view

**Comment by FOIMonkey** [comment]
2014 election results/list of deputies by party: http://www.gbissau.com/?page_id=11253
