### ISSUE TITLE
Japan

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#654]
http://www.shugiin.go.jp/internet/itdb_english.nsf/html/statics/member/mem_a.htm (by letter)

**Comment by struan** [comment]
I'm looking at this.

**Comment by struan** [comment]
Scraper at: https://morph.io/struan/japan

**Comment by tmtmtmtm** [comment]
Thanks @struan. Can you also split the honorific_prefix off the names (and set gender from those where appropriate)?
