### ISSUE TITLE
North Korea

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#656]
Someone seems to be working on this at:

https://ko.wikipedia.org/wiki/%EC%82%AC%EC%9A%A9%EC%9E%90:%EB%B3%B4%EB%9E%80%EB%93%9C

**Comment by FOIMonkey** [comment]
That's the 12th SPA. A list of delegates at the 13th is here: http://www.dailynk.com/korean/read.php?num=102886&cataId=nk00100 Article gives the source as being the North Korean electoral commission. Data tallies with that given in other south korean news sources around that date.

**Comment by tmtmtmtm** [comment]
Is that format "DistrictNumber DistrictName PersonName"?

**Comment by FOIMonkey** [comment]
Yes, taking the first entry as an example:
제...호 means number eg 제1호 = number 1.
선거구 means precinct, so the bit before that is the place name eg 만경대선거구 = Mangyongdae precinct.
Last column is the name eg 박정남 = Bak Jeongnam

**Comment by tmtmtmtm** [comment]
Great, thanks!

**Comment by tmtmtmtm** [comment]
I wonder what happened to number 111…?

**Comment by FOIMonkey** [comment]
The MP for 111 is Kim Jong-Un himself: http://www.telegraph.co.uk/news/worldnews/asia/northkorea/10687009/Kim-Jong-un-secures-unsurprising-100-per-cent-victory-in-North-Korea-election.html

**Comment by tmtmtmtm** [comment]
Hah, excellent. After writing a scraper for this I actually found https://en.wikipedia.org/wiki/North_Korean_parliamentary_election,_2014, so have switched to using that instead for now, and have opened https://github.com/everypolitician/everypolitician-data/issues/850 for combining them later.
