### ISSUE TITLE
Laos

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#658]
http://na.gov.la/

**Comment by Maddock-** [comment]
http://na.gov.la/index.php?option=com_content&view=category&id=28&Itemid=223&lang=en

Is a list of names by province - available in both Lao and English. Wikipedia tells me Laos is a single-party state, which would explain why I couldn't find that information.

**Comment by tmtmtmtm** [comment]
Great, thanks!

**Comment by tmtmtmtm** [comment]
* https://en.wikipedia.org/wiki/National_Assembly_(Laos)
* https://www.wikidata.org/wiki/Q1188525
* Seats: 132
* Last election 2011: https://en.wikipedia.org/wiki/Elections_in_Laos

**Comment by tmtmtmtm** [comment]
@ChrisMaddock — according to https://en.wikipedia.org/wiki/Elections_in_Laos, although it's a single-party state, there are 4 (approved) non-partisan members. Don't suppose you happened to notice anywhere that would say who those are?

**Comment by tmtmtmtm** [comment]
Now live: http://everypolitician.org/laos/

Separate ticket opened for the Party information: #796

**Comment by ChrisMaddock** [comment]
@tmtmtmtm No, I'm afraid not. If it's still an open issue next week, I may have more of a dig around.
