### ISSUE TITLE
Lebanon

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#659]
https://www.lp.gov.lb/

**Comment by dracos** [comment]
2009 list here: https://www.lp.gov.lb/HouseDetails.aspx?id=1 (including note of some deaths)
2005 list here: https://www.lp.gov.lb/HouseDetails.aspx?id=2
Election site here: http://www.elections.gov.lb/Elections-Results/2009-Real-time-Results.aspx (mentions a 2012 by election?)
Wikipedia list here: https://en.wikipedia.org/wiki/Members_of_the_2009–17_Lebanese_Parliament and https://en.wikipedia.org/wiki/Members_of_the_2005–09_Lebanese_Parliament

**Comment by tmtmtmtm** [comment]
Excellent, thanks!

**Comment by tmtmtmtm** [comment]
Also in the Arabic Wikipedia (with more wikidata links): https://ar.wikipedia.org/wiki/مجلس_النواب_اللبناني
