### ISSUE TITLE
Nagorno-Karabakh

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#663]
* https://en.wikipedia.org/wiki/National_Assembly_(Nagorno-Karabakh_Republic)
* https://www.wikidata.org/wiki/Q166619
* Seats: 33

**Comment by FOIMonkey** [comment]
There is a list of deputies on the national assembly by party here: http://tinyurl.com/q9j7boh

**Comment by tmtmtmtm** [comment]
Thanks @FOIMonkey!

**Comment by struan** [comment]
I'll take a look at this.

**Comment by struan** [comment]
Looking at this a bit more this only lists the deputies elected under the proportional system. There are a further 11 elected under the majoritarian system who don't seem to be listed here. There's some other names listed in the text but I don't understand enough about the electoral system and I can't find any corroborating data to know if they were elected or not.

Scraper for the PR members here FWIW: https://morph.io/struan/national_assembly_nagorno-karabakh_members

**Comment by FOIMonkey** [comment]
There is a (russian) version of the list of all the deputies here, that includes the additional 11: http://www.artsakhtert.com/rus/2012-02-08-10-32-17/2012-02-08-11-51-15/4546---------3--2015------

**Comment by FOIMonkey** [comment]
English version here, though without party info: http://nankr.am/deputy/
