### ISSUE TITLE
Palau

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#665]
http://palaugov.org/

http://www.worldwalkabout.com/Clientfiles/NEW%20GOV%20WEBSITE/HouseofDelegates/hsedelegates.html ?

**Comment by confirmordeny** [comment]
http://www.palauoek.com/?page_id=19 - list of senators

**Comment by FOIMonkey** [comment]
https://en.wikipedia.org/wiki/Palauan_general_election,_2012

**Comment by tmtmtmtm** [comment]
Thanks @confirmordeny and @FOIMonkey — Wikipedia doesn't add much on this one, and the official site looks easy enough to scrape, so I'll give that a shot first.

**Comment by tmtmtmtm** [comment]
Hmmm. Although both are only for the Senate, and I'd prefer lower houses first…

http://www.palauoek.com/wp-content/uploads/2014/04/SB-9-9.pdf shows the list of Representatives down the left-hand side of their notepaper!

And from http://www.mvariety.com/cnmi/cnmi-news/local/69073-palau-lawmakers-seek-advice-from-nmi-officials-on-casino-investment we get a list of Alexander Merep, Mario Gulibert, Marhence Madrangchar, Masasinge Arurang, Marino Ngemaes, Lentcer Basilius, Ngiraiwet, Yutaka Gibbons Jr., Ongidobel, Jonathan Isechal, Lee Otobed and Noah Kemesong + Frank Kyota, Gibson Kanai, and Sebastian Marino.

**Comment by FOIMonkey** [comment]
Election results for house delegates are here that verify the above: http://www.oceaniatv.net/republic-of-palau-2012-elections-candidates/
