### ISSUE TITLE
Saint Barthélemy

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#671]
* https://en.wikipedia.org/wiki/Territorial_Council_of_Saint-Barth%C3%A9lemy

**Comment by confirmordeny** [comment]
19 member territorial council - election results for 2007 here:
http://www.st-barths.com/en/news/310/112/Results-of-Territorial-Elections-Victory-for-St-Barth-d-Abord-2007.html

**Comment by confirmordeny** [comment]
There would have been a more recent election but I can't find a good source. See also http://journaldesaintbarth.com/journaux/pdf/Journal966.pdf which is cited from Wikipedia.

**Comment by FOIMonkey** [comment]
https://fr.wikipedia.org/wiki/Conseil_territorial_de_Saint-Barth%C3%A9lemy#Mandature_mars_2012_-_2017

**Comment by tmtmtmtm** [comment]
Bingo. Thanks @FOIMonkey and @confirmordeny
