### ISSUE TITLE
Saint Helena

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#672]
* http://www.sainthelena.gov.sh/councils/
* https://en.wikipedia.org/wiki/Legislative_Council_of_Saint_Helena

**Comment by confirmordeny** [comment]
This webpage has photos and biographies http://www.sainthelena.gov.sh/your-council/

**Comment by tmtmtmtm** [comment]
Excellent, thanks. https://en.wikipedia.org/wiki/Saint_Helena_general_election,_2013 matches that, though none of them appear to have their own pages there (or at least aren't linked), so no Wikidata to be had.
