### ISSUE TITLE
Saint Martin (fr)

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#673]
http://www.com-saint-martin.fr/JO/Pages/Conseil-Territorial.aspx

**Comment by FOIMonkey** [comment]
https://fr.wikipedia.org/wiki/Conseil_territorial_de_Saint-Martin#Composition_du_conseil_territorial

**Comment by tmtmtmtm** [comment]
Nice — that'll be an easy one to scrape :)

Thanks

**Comment by tmtmtmtm** [comment]
Scraper at https://morph.io/tmtmtmtm/saint-martin-territorial-council

**Comment by tmtmtmtm** [comment]
And wikidata at https://morph.io/tmtmtmtm/saint-martin-territorial-council-wikidata
