### ISSUE TITLE
Sark

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#676]
Only Wikipedia with a page on the legislature itself seems to be Poland:
* https://pl.wikipedia.org/wiki/Chief_Pleas
* https://www.wikidata.org/wiki/Q9189683

Seats: 30

**Comment by andylolz** [comment]
Election results: http://www.gov.sark.gg/election_results.html

According to [wikipedia](https://en.wikipedia.org/wiki/Sark#Transition_to_new_system_of_government):

> […] a 30-member chamber, with 28 members elected in island-wide elections, one hereditary member and one member appointed for life.

**Comment by tmtmtmtm** [comment]
Thanks. http://www.gov.sark.gg/conseillers.html is probably easier to scrape, and includes email addresses too.

**Comment by tmtmtmtm** [comment]
Wikipedia's versions are quite easy to parse too:
* https://en.wikipedia.org/wiki/Sark_general_election,_2014 
* https://en.wikipedia.org/wiki/Sark_general_election,_2012
* https://en.wikipedia.org/wiki/Sark_general_election,_2010
* https://en.wikipedia.org/wiki/Sark_general_election,_2008
