### ISSUE TITLE
Senegal

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#678]
* http://www.assemblee-nationale.sn/ is the Assembly site, but is just a Joomla holding page
* http://www.gouv.sn/-L-Assemblee-nationale-.html is the page about the Assembly on the Government site, but with no member info
* Last election: 2012 — https://fr.wikipedia.org/wiki/Élections_législatives_sénégalaises_de_2012

**Comment by FOIMonkey** [comment]
https://fr.wikipedia.org/wiki/Liste_des_d%C3%A9put%C3%A9s_du_S%C3%A9n%C3%A9gal_%C3%A9lus_en_2012

**Comment by tmtmtmtm** [comment]
Excellent! Thanks @FOIMonkey

**Comment by tmtmtmtm** [comment]
* https://en.wikipedia.org/wiki/National_Assembly_(Senegal)
* https://www.wikidata.org/wiki/Q1853640
* Seats: 150

**Comment by tmtmtmtm** [comment]
Scraper: https://morph.io/tmtmtmtm/senegal-national-assembly

**Comment by tmtmtmtm** [comment]
Wikidata scraper: https://morph.io/tmtmtmtm/senegal-national-assembly-wikidata
