### ISSUE TITLE
Somaliland

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#680]

**Comment by confirmordeny** [comment]
https://web.archive.org/web/20141022135723/http://www.parliament.gov.so/index.php/en/membersparliament-3 (a web archives page from October 2014)

See also: http://goobjoog.com/english/?p=10231

**Comment by tmtmtmtm** [comment]
Oooh, nice find. Unfortunately they don't seem to have scraped any of the following pages though :(

**Comment by FOIMonkey** [comment]
http://www.somalilandparliament.com/the-headers/

**Comment by FOIMonkey** [comment]
http://somalilandparliament.net/index.php/members-of-the-hor/65-members-by-constituency-a-party/56-members-of-the-parliament Less broken - think these two are for the upper house.
