### ISSUE TITLE
Syria

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#684]
http://parliament.gov.sy/arabic/index.php

**Comment by Maddock-** [comment]
http://parliament.gov.sy/arabic/index.php?node=210#

Current members.

**Comment by tmtmtmtm** [comment]
Yay, thanks!

**Comment by tmtmtmtm** [comment]
* https://en.wikipedia.org/wiki/People%27s_Council_of_Syria
* https://www.wikidata.org/wiki/Q1372196
* 250 members
* Last election: https://en.wikipedia.org/wiki/Syrian_parliamentary_election,_2012
