### ISSUE TITLE
Timor-Leste

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#687]
http://parlamento.tl/

**Comment by confirmordeny** [comment]
Yes specifically - http://parlamento.tl/deputadus/2012/pt/deputados.php

**Comment by tmtmtmtm** [comment]
Perfect, thanks!

**Comment by tmtmtmtm** [comment]
* https://en.wikipedia.org/wiki/National_Parliament_(East_Timor)
* https://www.wikidata.org/wiki/Q680806
* 65 seats
* Current Term = 3rd
