### ISSUE TITLE
Trinidad and Tobago

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#690]
http://ttparliament.org/

**Comment by Maddock-** [comment]
All previous parliaments easy to parse here: http://ttparliament.org/members.php?mid=26

An election took place yesterday, the results are available in a lovely parsable pdf... 
http://www.ebctt.com/wp-content/uploads/Election-Agents-20050906.pdf 

Or on the only slightly better Wikipedia article:
https://en.wikipedia.org/wiki/Trinidad_and_Tobago_general_election,_2015

I imagine it might be more productive to wait for the government website to be updated and use the same parser!

(!) the results are on Wikipedia

**Comment by tmtmtmtm** [comment]
Yep, I'll leave this a while and see if the official data updates. Thanks.

**Comment by tmtmtmtm** [comment]
Closed by PRs linked above.
