### ISSUE TITLE
Turkmenistan

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#691]
http://mejlis2.bushluk.com/tm/parliamentaries/convocations/current/members-list/

(also includes historic members)

**Comment by Maddock-** [comment]
http://na.gov.la/index.php?option=com_content&view=category&id=28&Itemid=223&lang=en

Is a list of names by province - available in both Lao and English. Wikipedia tells me Laos is a single-party state, which would explain why I couldn't find that information.

**Comment by tmtmtmtm** [comment]
@maddock: I this this was meant to be a comment on https://github.com/everypolitician/everypolitician-data/issues/658 instead :)

**Comment by Maddock-** [comment]
@tmtmtmtm Whoops...thanks!

**Comment by tmtmtmtm** [comment]
* https://en.wikipedia.org/wiki/Assembly_of_Turkmenistan
* https://www.wikidata.org/wiki/Q630145
* 125 seats
* Last Election: 2013 https://en.wikipedia.org/wiki/Turkmenistani_parliamentary_election,_2013
