### ISSUE TITLE
Uganda

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#692]
http://www.parliament.go.ug/new/

**Comment by duncanfwalker** [comment]
http://www.parliament.go.ug/mpdata/mps.hei looks like it's got quite a lot of information on. Is there somewhere I should look to see which fields we are interested in or should I assume the more the better?

**Comment by tmtmtmtm** [comment]
Yep, looks good!

http://everypolitician.org/submitting.html lists the fields that will import cleanly.

Others (like education history etc) are worth grabbing if they're in a vaguely standardised form, so that we can potentially add them later, but they're not as important, so if they're tricky, don't worry too much about them.

**Comment by duncanfwalker** [comment]
I had an initial go at a scraper here: 
https://morph.io/duncanfwalker/uganda-parliament-scraper

**Comment by tmtmtmtm** [comment]
Excellent, thanks!

Can you grab the Politicial Party line too? That's quite a useful one :)

And it would be good if you could convert the date_of_birth to YYYY-MM-DD as well. But otherwise looks great.

**Comment by tmtmtmtm** [comment]
Oh, and a 'source' for each person that has the URL you scraped for them would also be useful.

**Comment by duncanfwalker** [comment]
sure, will do

**Comment by duncanfwalker** [comment]
It's update now with those three changes (source, dob format and party)

**Comment by tmtmtmtm** [comment]
Excellent. I've just pushed that live: http://everypolitician.org/uganda/ 

Thanks a lot!

**Comment by duncanfwalker** [comment]
Thanks
