### ISSUE TITLE
United Arab Emirates

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#693]
https://www.almajles.gov.ae/Pages/FNCHome.aspx

**Comment by Maddock-** [comment]
40 members of the Federal National Council available at this link. Looks pretty horrible to parse however, and there doesn't seem to be any 'area' information.

**Comment by tmtmtmtm** [comment]
@Maddock- I'm having some difficulty finding the page with the members — do you have the URL to that?

**Comment by Maddock-** [comment]
@tmtmtmtm Sorry...I'm not doing very well tonight!

https://www.almajles.gov.ae/MembersProfiles/Pages/MemProfile.aspx

**Comment by tmtmtmtm** [comment]
Erk, yeah — that's not going to be fun to scrape at all. Hopefully PhantomJS can cope with it…

but at least now we know where to find the data — Thanks!
