### ISSUE TITLE
United States

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#694]
http://www.house.gov/

**Comment by tmtmtmtm** [comment]
All data as JSON: https://github.com/unitedstates/congress-legislators

See also: https://sunlightlabs.github.io/congress/

**Comment by JoshData** [comment]
Hello. I've written a converter for the [congress-legislators YAML](https://github.com/unitedstates/congress-legislators) into the EP CSV format. Can EP run this on its own as part of its build process (i.e. clone the repo, activate the Python environment/install dependencies, run the Python script), or do I definitely need to host the CSV files?

**Comment by tmtmtmtm** [comment]
@JoshData that's superb, thanks! We can definitely find a way to run that ourselves if you don't want to host the files. 

I'm assuming it'll be fairly simple to do something similar for the historic members too?

**Comment by JoshData** [comment]
Great.

I didn't realize you wanted historical too. That'll require a bit of a change, and I'm not sure we can reliably fill in `term` going back a few hundred years. Let's start with this and if it all works I can look at adding historical data?

**Comment by tmtmtmtm** [comment]
Sure thing. We're concentrating on current for now, but where possible we also like to get as much historic data as possible too. But we can definitely backfill that later. 

Will hopefully get some time this afternoon to look into how to integrate this, but might end up being tomorrow morning.

**Comment by JoshData** [comment]
Cool. No hurry on my account.

**Comment by tmtmtmtm** [comment]
@JoshData — the easiest way to slot this into our process would be to run it on morph.io, fetching the YAML directly from https://raw.githubusercontent.com/unitedstates/congress-legislators/master/legislators-current.yaml (etc) and writing each row to the database, rather than spitting out CSV directly. (Similarly to https://github.com/mhl/lithuania-politician-scraper/blob/master/scraper.py)

If you were up for doing this yourself, that would be superb, otherwise I can look into doing it myself (or more likely getting someone who's more familiar with the python environment to do so!)

**Comment by JoshData** [comment]
It's far easier for me to just run the conversion on a cron job and post the file to a public URL.

**Comment by tmtmtmtm** [comment]
Hi @JoshData (and @mhl),

I'm not really sure what the issues were getting this running on morph using Python, but I [ported to Ruby](https://github.com/tmtmtmtm/us-congress-members/blob/master/scraper.rb) and everything seems to be [working fine now](https://morph.io/tmtmtmtm/us-congress-members).

I took a slightly different approach in a few ways:
* I didn't build the human-readable Area information, but rather generated [OCD Division IDs](https://github.com/opencivicdata/ocd-division-ids), as those mappings already exist for the US (the results are a little more verbose, but we can live with that for now, and look into ways of fixing that at a different level)
* I used the 'official_full' name entry, rather than building from parts — I'm guessing the code is to cope with that not being filled for older entries, so I'll need to replicate that when we add historic data, but it seems to be fine for all current members.
* I made a [separate 'scraper'](https://morph.io/tmtmtmtm/us-congress-members-social-media) for the social media accounts. It's trivial for us to just merge those sources when building, and this way we can update both independently etc.
* I pulled in _all_ the identifiers and social media accounts rather than just the ones we document as wanted (this is something I've been doing a lot when getting info from Wikidata too, and I haven't modified the docs yet as I'm not 100% sure how I'm going to expose them all — but at least most of them end up in the raw Popolo that's generated for anyone using that, and the others will be in the morph database for when we work out how to import them)

I've also added two scrapers ([House](https://morph.io/tmtmtmtm/us-representatives-wikidata} | [Senate](https://morph.io/tmtmtmtm/us-senators-wikidata)] that use the Wikipedia references included here to suck extra information out of Wikidata — though I haven't merged that data in yet. I'll probably do so later today.

But all the current data is now live at http://everypolitician.org/united-states-of-america/

Thanks for your help and patience!

**Comment by tmtmtmtm** [comment]
Closed by #760

**Comment by JoshData** [comment]
Cool.
