### ISSUE TITLE
Vanuatu

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#695]
http://parliament.gov.vu/

**Comment by Maddock-** [comment]
http://parliament.gov.vu/index.php/memebers/

Lists all members with basic details. Additional information for some more recent members on separate pages. Note members who died mid-term are listed separately at end of page, and there doesn't seem to be any start/end of term data for them or their replacements.

**Comment by tmtmtmtm** [comment]
Excellent. That looks pretty easy to grab — will try to do so this afternoon or tomorrow morning. Thanks!
