### ISSUE TITLE
Vietnam

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#697]
http://quochoi.vn/en-US/Pages/default.aspx

**Comment by FOIMonkey** [comment]
https://vi.wikipedia.org/wiki/Danh_s%C3%A1ch_%C4%91%E1%BA%A1i_bi%E1%BB%83u_Qu%E1%BB%91c_h%E1%BB%99i_Vi%E1%BB%87t_Nam_kh%C3%B3a_XIII

**Comment by tmtmtmtm** [comment]
Ooh, nice! The changing format half-way through, and the inclusion of some people who didn't win in a couple of places is going to make this one a little awkward to scrape, but it's a good find.
