### ISSUE TITLE
Yemen

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#698]
* https://en.wikipedia.org/wiki/House_of_Representatives_(Yemen)
* https://en.wikipedia.org/wiki/Next_Yemeni_parliamentary_election
* http://www.aljazeera.com/news/2015/02/yemen-feuding-parties-agree-transitional-council-150220065456873.html

**Comment by FOIMonkey** [comment]
http://www.parliament.gov.ye/Members.htm

**Comment by tmtmtmtm** [comment]
Nice find @FOIMonkey. Don't suppose you can happen to find a version with party info too? :)

**Comment by FOIMonkey** [comment]
Try this: http://www.ypwatch.org/members.php

**Comment by tmtmtmtm** [comment]
@FOIMonkey: Thanks — that one was quite nice to scrape!
