### ISSUE TITLE
UK: Additional Alternative Names

### ISSUE THREAD

**Issue by ajparsons** [everypolitician/everypolitician-data#71982]
# Problem with Existing Data

## Legislature

UK Parliament

## Problem

IPSA use names for MPs that differ slightly from EP names when publishing datasets like expenses.

## Proposed Solution

The 36 names that differ between sources have been isolated in this spreadsheet:

https://docs.google.com/spreadsheets/d/1yHQaXD124KhiUD1VCktUo1E-ABmXGdtenPGLbpRKj7Y/edit#gid=0

These should be imported as alternate under 'other_names'.

**Comment by tmtmtmtm** [comment]
@ajparsons is this a problem because you're trying to match the datasets by name? Do IPSA use any identifiers that we could add to the dataset as well/instead?

**Comment by ajparsons** [comment]
@tmtmtmtm They don't, which is a pain. This is more that these are semi-official names that should probably be included in some form (so that matching on name + other keys) is possible.

**Comment by tmtmtmtm** [comment]
@ajparsons In that case, your best bet is probably to add them as aliases in Wikidata, as I've done for the first example:
  https://www.wikidata.org/w/index.php?title=Q689383&type=revision&diff=683748540&oldid=658895605

Those will then flow through automatically into EveryPolitician at the next update.

If you wanted to be more 'correct' from a Wikidata POV, you could add them using `described by source (P1343)`, or `described at URL (P973)` with a suitable name qualifier, but that route wouldn't yet flow to EP (though it shouldn't be too difficult to make it do so, should you decide to add them like that)
