### ISSUE TITLE
Open graph image

### ISSUE THREAD

**Issue by MyfanwyNixon** [everypolitician/everypolitician-data#727]
Could we add an image for when we (or indeed other people) share links on Facebook? At the moment it's blank.

https://developers.facebook.com/docs/sharing/best-practices#tags

**Comment by tmtmtmtm** [comment]
@zarino is this easy to do?

**Comment by zarino** [comment]
@tmtmtmtm – Pretty simple, here's an example of the code we added for the same thing in YouNextRepresentative: https://github.com/mysociety/yournextrepresentative/pull/434/files

**Comment by tmtmtmtm** [comment]
@davewhiteland you want to have a go at this? I can do it, otherwise, but I'd rather put more countries live :)

**Comment by zarino** [comment]
@tmtmtmtm I'm doing it now.

**Comment by tmtmtmtm** [comment]
Oh, great! Thanks @zarino :dancers:

**Comment by zarino** [comment]
@tmtmtmtm – am I right in thinking this should be implemented in the `layout.erb` file of everypolitician/viewer-sinatra? Like https://github.com/everypolitician/viewer-sinatra/pull/593 ?

**Comment by tmtmtmtm** [comment]
@zarino Yep, that looks right. This ready to merge or still just testing?

**Comment by zarino** [comment]
Still testing.

**Comment by tmtmtmtm** [comment]
Closed by https://github.com/everypolitician/viewer-sinatra/pull/593
