### ISSUE TITLE
Switzerland

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#74]
Official: http://www.parlament.ch/E/ORGANE-MITGLIEDER/NATIONALRAT/MITGLIEDER-NR-A-Z/Pages/default.aspx

**Comment by briatte** [comment]
Their [open data service](http://ws.parlament.ch/) is [easy to process](https://github.com/briatte/swparl/blob/master/data.r). Have a look at

http://ws.parlament.ch/councillors/historic?lang=fr

which can return JSON directly.

**Comment by tmtmtmtm** [comment]
Oh, that is indeed very nice, thanks!

It's a little bit irritating that the current term data is in a slightly different format from historic terms, but it's still a pleasure to work with compared to most countries!
