### ISSUE TITLE
Uganda: Reverse the names in the scraper

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician-data#7496]
The new data we got from Colin at Parliament Watch Uganda has the names in what I believe is the correct order, but the scraper is pulling them in "backwards":

Parliament watch on the left, existing scraper output on the right:

![screen shot 2016-04-07 at 17 28 07](https://cloud.githubusercontent.com/assets/22996/14356709/3ce90a6e-fce6-11e5-8738-79bbd9d74cb2.png)

**Comment by octopusinvitro** [comment]
Fixed in https://github.com/everypolitician-scrapers/uganda-parliament-scraper/commit/3b46766ba25268912ed711acee5ef9142509d184
