### ISSUE TITLE
Croatia: missing gender values in term-8.csv

### ISSUE THREAD

**Issue by marfi** [everypolitician/everypolitician-data#7748]
7.csv misses just a single gender value, howeve in https://github.com/everypolitician/everypolitician-data/blob/master/data/Croatia/Sabor/term-8.csv there's almost no gender data. Can we do something about it?

**Comment by tmtmtmtm** [comment]
The main options for this are:

1. Find an official source for this data — it doesn't seem to be on the official Parliament site (in either English or Croatian), but I may just be missing something, or perhaps there's somewhere else that has this information in bulk
2. Add it to Wikidata pages for the people — unfortunately very few of the Croatian MPs seem to have Wikipedia pages (in any language), but it's certainly possible to add them directly to Wikidata, so it might be a good way to handle the single missing person from the 7th Term
3. Get more people playing http://www.gender-balance.org/countries/Croatia

**Comment by tmtmtmtm** [comment]
See also https://github.com/everypolitician/everypolitician-data/pull/7749
