### ISSUE TITLE
United Kingdom: Debbie Abrahams phone/fax is incorrectly scraped.

### ISSUE THREAD

**Issue by jacksonj04** [everypolitician/everypolitician-data#7809]
In the [56th Parliament](http://everypolitician.org/uk/commons/term-table/56.html#facet=contacts), Debbie Abrahams has her phone/fax numbers parsed into the same field:

<img width="387" alt="screen shot 2016-04-12 at 11 14 03" src="https://cloud.githubusercontent.com/assets/619082/14456968/a5cad50a-009f-11e6-948c-b6014a36f038.png">

**Comment by chrismytton** [comment]
Looks like this is what is being output from [data.parliament.uk](http://data.parliament.uk/membersdataplatform/services/mnis/members/query/House=Commons%7CIsEligible=true/Addresses/) 😕 

![screen shot 2016-04-19 at 10 33 00](https://cloud.githubusercontent.com/assets/22996/14632662/3be7fa16-061a-11e6-96c4-2ab51dafff43.png)

**Comment by jacksonj04** [comment]
/me places hands in head and weeps gently.

Feel free to close as a non-issue.
