### ISSUE TITLE
Latvia: Terms 10 and 11 data

### ISSUE THREAD

**Issue by marfi** [everypolitician/everypolitician-data#7957]
Looking at the pictures URLs of the Latvian 12 term representatives, I was able to find the structure for the 10th and 11th term:

http://titania.saeima.lv/personal/deputati/saeima10_depweb_public.nsf/deputies?OpenView&lang=LV&count=1000
http://titania.saeima.lv/personal/deputati/saeima11_depweb_public.nsf/deputies?OpenView&lang=LV&count=1000

The list is also available in English by changing the lang=LV param:

http://titania.saeima.lv/personal/deputati/saeima10_depweb_public.nsf/deputies?OpenView&lang=EN&count=1000
http://titania.saeima.lv/personal/deputati/saeima11_depweb_public.nsf/deputies?OpenView&lang=EN&count=1000

Let me know how I can help you expand the scraper for Latvia to include them. I will be looking around and trying to figure it out for myself in the meantime.

**Comment by tmtmtmtm** [comment]
Hi @marfi 

The Latvian scraper wasn't really very good generally, as the lists on the official site were all heavily JavaScript-based. I worked out how to get at the underlying data without waiting for it to be rendered, and rebuilt the scraper to be much simpler and faster. As a result of this it was also trivial to pick up the list of people who have resigned mid-way through the current term, as well as the people from each of the two previous terms. That data is all now live: http://everypolitician.org/latvia/
