### ISSUE TITLE
Angola

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#87]
http://www.parlamento.ao/web/guest/deputados-e-grupos-parlamentares/deputados/lista#http://www.parlamento.ao/glue/AN_Navigation.jsp?

Scraping the site itself is easy (and there doesn't appear to be any extra information on the Person page that's not on the List page) — but the next/prev links are JS driven, so we'll probably need to use Morph's [Phantom.js support](https://www.openaustraliafoundation.org.au/2015/03/17/scraping-javascript-sites-with-morph-io/)

**Comment by duncanparkes** [comment]
I can have a look at this if you like  - I'm in PyExecJS mode right now.

**Comment by tmtmtmtm** [comment]
I already did this one yesterday using PhantomJS: https://morph.io/tmtmtmtm/angola-national-assembly

Morph is playing up for all my scrapers at the minute, but other than that it seems to be running cleanly,

**Comment by tmtmtmtm** [comment]
Closed by #145
