### ISSUE TITLE
Provide a CSV containing the current memberships of a term

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician-data#918]
At the moment we provide a CSV for each term which contains all of the memberships for a given term. So if someone has changed party during a term then there will be two rows for them in the term CSV, one for each party.

It would be useful if there was a file which contained a snapshot of the current state of the legislature, i.e. each person just appears in there once with their current party information. Something like `current.csv` in the legislature directory, probably linked to from the `countries.json` file.

**Comment by tmtmtmtm** [comment]
@chrismytton: You should probably move this to https://github.com/everypolitician/everypolitician/issues — the issues on this repo are really only for country-specific scraping tasks (maybe also good to use the new [github issues templates](https://github.com/blog/2111-issue-and-pull-request-templates) to add a message to that effect here too…)

**Comment by chrismytton** [comment]
Moved to here - https://github.com/everypolitician/everypolitician/issues/338

**Comment by chrismytton** [comment]
Have also added an issue template to this repo:

![screen shot 2016-03-10 at 10 39 46](https://cloud.githubusercontent.com/assets/22996/13665376/7815a282-e6ac-11e5-81c5-08e6e560582d.png)
