### ISSUE TITLE
`lang` in `person.other_names` of json output

### ISSUE THREAD

**Issue by andylolz** [everypolitician/everypolitician-data#921]
Json output for various legislatures (including [the UK Commons](https://github.com/everypolitician/everypolitician-data/blob/master/data/UK/Commons/ep-popolo-v1.0.json)) lists transliterated versions of person names in the `other_names` field.

It looks awesome:

![screen shot 2015-10-01 at 18 03 02](https://cloud.githubusercontent.com/assets/464193/10227706/cd8200ea-6866-11e5-83c9-d772fb953f52.png)

…But is this valid Popolo? I can’t see anything in [the EP docs](http://everypolitician.org/data_structure.html) about this, and I’m not sure I really understand [the relevant bit in the Popolo docs](http://www.popoloproject.com/appendices/multilingualization.html).

**Comment by tmtmtmtm** [comment]
Valid Popolo, sure. The _correct_ way to do it in Popolo — that's a much more difficult question.

This is more of an issue with JSON than with Popolo (as the Popolo docs you've linked alludes to in passing). Were we using JSON-LD as our primary representation, then this would be a solved issue. And it's 90% likely that we'll end up switching to that in large part for this very reason. But I didn't want to wait until then to be able to expose these, so decided to just throw them in here with a 'note' field that people could filter on (in either direction!) It's not mentioned in the EP docs yet, as it's largely a transitional experiment. 

Though we _are_ going to document the newly exposed (#920) versions of them in a `names.csv` file for each legislature…

**Comment by andylolz** [comment]
Ahhh, okay I see. Thanks @tmtmtmtm!
