### ISSUE TITLE
UK: Wrong wikidata id for constituency

### ISSUE THREAD

**Issue by ajparsons** [everypolitician/everypolitician-data#92318]
## Legislature

UK Parliament

## Problem

Area - West Suffolk (uk.org.publicwhip/cons/628) has wrong wikidata ID.

Has 19th century West Sussex (Q11797292) - should be Q874416

**Comment by tmtmtmtm** [comment]
Thanks @ajparsons — that's now fixed. If you see any others, please point them out (now that I'm back working on this, I should be able to correct them very quickly.)
